// Code generated by api-contract. DO NOT EDIT.
// 修改本文件请同步更新：
//   - docs/04-api-contract.md
//   - web/src/types/api.ts
package types

// ---------------------------------------------------------------------------
// 通用响应包装
// ---------------------------------------------------------------------------

// APIResponse 是所有 HTTP 接口的统一响应信封。
// 成功时 code 为空字符串（omitempty 省略），data 携带载荷。
// 失败时 code 为 ERR_XXX_YYY，data 为空，message 和 details 携带错误信息。
type APIResponse[T any] struct {
	Code      string `json:"code,omitempty"`
	Data      T      `json:"data,omitempty"`
	Message   string `json:"message,omitempty"`
	Details   any    `json:"details,omitempty"`
	RequestID string `json:"request_id,omitempty"`
}

// PagedResponse 分页响应（嵌套在 APIResponse.Data 中）。
type PagedResponse[T any] struct {
	Items    []T   `json:"items"`
	Total    int64 `json:"total"`
	Page     int   `json:"page"`
	PageSize int   `json:"page_size"`
}

// ---------------------------------------------------------------------------
// 枚举类型
// ---------------------------------------------------------------------------

// UserRole 用户角色。
type UserRole string

const (
	RoleAdmin UserRole = "admin"
	RoleUser  UserRole = "user"
)

// SubType 订阅类型。
type SubType string

const (
	SubTypeURL    SubType = "url"
	SubTypeUpload SubType = "upload"
	SubTypeManual SubType = "manual"
)

// SyncStatus 订阅同步状态。
type SyncStatus string

const (
	SyncStatusOK      SyncStatus = "ok"
	SyncStatusError   SyncStatus = "error"
	SyncStatusPending SyncStatus = "pending"
)

// NodeProtocol 节点协议类型（12 种）。
type NodeProtocol string

const (
	ProtocolVmess     NodeProtocol = "vmess"
	ProtocolVless     NodeProtocol = "vless"
	ProtocolSS        NodeProtocol = "ss"
	ProtocolSSR       NodeProtocol = "ssr"
	ProtocolTrojan    NodeProtocol = "trojan"
	ProtocolHysteria  NodeProtocol = "hysteria"
	ProtocolHysteria2 NodeProtocol = "hysteria2"
	ProtocolTUIC      NodeProtocol = "tuic"
	ProtocolWireguard NodeProtocol = "wireguard"
	ProtocolAnyTLS    NodeProtocol = "anytls"
	ProtocolSocks5    NodeProtocol = "socks5"
	ProtocolNaive     NodeProtocol = "naive"
)

// OperatorType 流水线算子类型（v1 六种）。
type OperatorType string

const (
	OpFilter      OperatorType = "filter"
	OpMap         OperatorType = "map"
	OpSort        OperatorType = "sort"
	OpDedupe      OperatorType = "dedupe"
	OpRegexRename OperatorType = "regex_rename"
	OpOutput      OperatorType = "output"
)

// RuleType 自定义规则类型。
type RuleType string

const (
	RuleTypeDNS           RuleType = "dns"
	RuleTypeRules         RuleType = "rules"
	RuleTypeRuleProviders RuleType = "rule-providers"
)

// RuleMode 规则注入模式。
type RuleMode string

const (
	RuleModeReplace RuleMode = "replace"
	RuleModePrepend RuleMode = "prepend"
	RuleModeAppend  RuleMode = "append"
)

// HookType JS 脚本钩子类型。
type HookType string

const (
	HookPreSaveNodes HookType = "pre_save_nodes"
	HookPostFetch    HookType = "post_fetch"
)

// AgentKind agent 种类。
type AgentKind string

const (
	AgentKindNative      AgentKind = "native"
	AgentKindNezhaCompat AgentKind = "nezha_compat"
)

// AgentStatus agent 在线状态。
type AgentStatus string

const (
	AgentStatusOnline   AgentStatus = "online"
	AgentStatusOffline  AgentStatus = "offline"
	AgentStatusDegraded AgentStatus = "degraded"
)

// ChannelKind 通知渠道类型（10 种）。
type ChannelKind string

const (
	ChannelTelegram   ChannelKind = "telegram"
	ChannelDiscord    ChannelKind = "discord"
	ChannelSlack      ChannelKind = "slack"
	ChannelEmail      ChannelKind = "email"
	ChannelBark       ChannelKind = "bark"
	ChannelGotify     ChannelKind = "gotify"
	ChannelWebhook    ChannelKind = "webhook"
	ChannelServerChan ChannelKind = "serverchan"
	ChannelPushDeer   ChannelKind = "pushdeer"
	ChannelIFTTT      ChannelKind = "ifttt"
)

// EventType 通知事件类型。
type EventType string

const (
	EventNodeOffline            EventType = "node_offline"
	EventTrafficThreshold       EventType = "traffic_threshold"
	EventSubscriptionSyncFailed EventType = "subscription_sync_failed"
	EventBackupCompleted        EventType = "backup_completed"
	EventLoginAnomaly           EventType = "login_anomaly"
	EventOTAAvailable           EventType = "ota_available"
	EventScriptAlert            EventType = "script_alert"
)

// EventStatus 通知投递状态。
type EventStatus string

const (
	EventStatusPending       EventStatus = "pending"
	EventStatusSent          EventStatus = "sent"
	EventStatusFailed        EventStatus = "failed"
	EventStatusSkippedDedupe EventStatus = "skipped_dedupe"
)

// ---------------------------------------------------------------------------
// 错误码
// ---------------------------------------------------------------------------

// ErrorCode 统一错误码类型。
type ErrorCode string

const (
	// AUTH
	ErrAuthInvalidPassword     ErrorCode = "ERR_AUTH_INVALID_PASSWORD"
	ErrAuthUserInactive        ErrorCode = "ERR_AUTH_USER_INACTIVE"
	ErrAuthTOTPRequired        ErrorCode = "ERR_AUTH_TOTP_REQUIRED"
	ErrAuthTOTPInvalid         ErrorCode = "ERR_AUTH_TOTP_INVALID"
	ErrAuthTOTPExpired         ErrorCode = "ERR_AUTH_TOTP_EXPIRED"
	ErrAuthRecoveryCodeInvalid ErrorCode = "ERR_AUTH_RECOVERY_CODE_INVALID"
	ErrAuthRecoveryExhausted   ErrorCode = "ERR_AUTH_RECOVERY_CODE_EXHAUSTED"
	ErrAuthTokenInvalid        ErrorCode = "ERR_AUTH_TOKEN_INVALID"
	ErrAuthTokenExpired        ErrorCode = "ERR_AUTH_TOKEN_EXPIRED"
	ErrAuthRateLimited         ErrorCode = "ERR_AUTH_RATE_LIMITED"
	ErrAuthBruteForceBlocked   ErrorCode = "ERR_AUTH_BRUTE_FORCE_BLOCKED"
	ErrAuthForbidden           ErrorCode = "ERR_AUTH_FORBIDDEN"

	// VALIDATION
	ErrValidationRequiredField ErrorCode = "ERR_VALIDATION_REQUIRED_FIELD"
	ErrValidationInvalidFormat ErrorCode = "ERR_VALIDATION_INVALID_FORMAT"
	ErrValidationOutOfRange    ErrorCode = "ERR_VALIDATION_OUT_OF_RANGE"
	ErrValidationRegexCompile  ErrorCode = "ERR_VALIDATION_REGEX_COMPILE"
	ErrValidationYAMLParse     ErrorCode = "ERR_VALIDATION_YAML_PARSE"
	ErrValidationSchemaMismatch ErrorCode = "ERR_VALIDATION_SCHEMA_MISMATCH"

	// NOT_FOUND
	ErrNotFoundUser         ErrorCode = "ERR_NOT_FOUND_USER"
	ErrNotFoundSubscription ErrorCode = "ERR_NOT_FOUND_SUBSCRIPTION"
	ErrNotFoundNode         ErrorCode = "ERR_NOT_FOUND_NODE"
	ErrNotFoundPipeline     ErrorCode = "ERR_NOT_FOUND_PIPELINE"
	ErrNotFoundRule         ErrorCode = "ERR_NOT_FOUND_RULE"
	ErrNotFoundScript       ErrorCode = "ERR_NOT_FOUND_SCRIPT"
	ErrNotFoundAgent        ErrorCode = "ERR_NOT_FOUND_AGENT"
	ErrNotFoundChannel      ErrorCode = "ERR_NOT_FOUND_CHANNEL"

	// CONFLICT
	ErrConflictUsername        ErrorCode = "ERR_CONFLICT_USERNAME"
	ErrConflictPipelineVersion ErrorCode = "ERR_CONFLICT_PIPELINE_VERSION"

	// PIPELINE
	ErrPipelineOperatorUnknown ErrorCode = "ERR_PIPELINE_OPERATOR_UNKNOWN"
	ErrPipelineOperatorParams  ErrorCode = "ERR_PIPELINE_OPERATOR_PARAMS"
	ErrPipelineRunTimeout      ErrorCode = "ERR_PIPELINE_RUN_TIMEOUT"

	// SCRIPT
	ErrScriptTimeout          ErrorCode = "ERR_SCRIPT_TIMEOUT"
	ErrScriptSandboxViolation ErrorCode = "ERR_SCRIPT_SANDBOX_VIOLATION"
	ErrScriptRuntimeError     ErrorCode = "ERR_SCRIPT_RUNTIME_ERROR"

	// AGENT
	ErrAgentTokenInvalid       ErrorCode = "ERR_AGENT_TOKEN_INVALID"
	ErrAgentOffline            ErrorCode = "ERR_AGENT_OFFLINE"
	ErrAgentCommandTimeout     ErrorCode = "ERR_AGENT_COMMAND_TIMEOUT"
	ErrAgentVersionUnsupported ErrorCode = "ERR_AGENT_VERSION_UNSUPPORTED" // §1.8: HTTP 426

	// INTERNAL
	ErrInternalDatabase ErrorCode = "ERR_INTERNAL_DATABASE"
	ErrInternalUnknown  ErrorCode = "ERR_INTERNAL_UNKNOWN"
)

// ---------------------------------------------------------------------------
// M-USER：用户与认证 DTO
// ---------------------------------------------------------------------------

// User 完整用户信息（仅 admin / 内部使用）。
type User struct {
	ID                string   `json:"id"`
	Username          string   `json:"username"`
	Role              UserRole `json:"role"`
	IsActive          bool     `json:"is_active"`
	Email             string   `json:"email,omitempty"`
	Locale            string   `json:"locale"`
	TOTPEnabled       bool     `json:"totp_enabled"`
	CreatedAt         int64    `json:"created_at"`
	UpdatedAt         int64    `json:"updated_at"`
}

// UserPublicProfile 面向前端的用户信息（不含敏感字段）。
type UserPublicProfile struct {
	ID          string   `json:"id"`
	Username    string   `json:"username"`
	Role        UserRole `json:"role"`
	Email       string   `json:"email,omitempty"`
	Locale      string   `json:"locale"`
	TOTPEnabled bool     `json:"totp_enabled"`
	CreatedAt   int64    `json:"created_at"`
}

// LoginRequest 登录请求。
type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// LoginResponse 登录成功响应（未启用 2FA）。
type LoginResponse struct {
	AccessToken string            `json:"access_token"`
	ExpiresAt   int64             `json:"expires_at"`
	User        UserPublicProfile `json:"user"`
}

// PendingTOTPResponse 密码验证通过但需要 2FA 时的响应。
type PendingTOTPResponse struct {
	PendingToken string `json:"pending_token"`
	ExpiresIn    int    `json:"expires_in"` // 秒
	TOTPRequired bool   `json:"totp_required"`
}

// VerifyTOTPRequest TOTP 验证请求。
type VerifyTOTPRequest struct {
	PendingToken string `json:"pending_token"`
	Code         string `json:"code"`
}

// VerifyRecoveryRequest 备份码验证请求。
type VerifyRecoveryRequest struct {
	PendingToken string `json:"pending_token"`
	Code         string `json:"code"`
}

// TOTPSetupResponse TOTP 初始化响应（含 QR Code）。
type TOTPSetupResponse struct {
	Secret     string `json:"secret"`      // base32 secret
	OTPAuthURI string `json:"otpauth_uri"` // otpauth://totp/...
	QRCodeURL  string `json:"qr_code_url"` // data:image/png;base64,...
}

// EnableTOTPRequest 启用 2FA 请求。
type EnableTOTPRequest struct {
	Code string `json:"code"`
}

// EnableTOTPResponse 启用 2FA 响应（含备份码，仅返回一次）。
type EnableTOTPResponse struct {
	BackupCodes []string `json:"backup_codes"`
}

// DisableTOTPRequest 关闭 2FA 请求。
type DisableTOTPRequest struct {
	Code     string `json:"code"`
	Password string `json:"password"`
}

// UpdateMeRequest 更新当前用户信息请求。
type UpdateMeRequest struct {
	Username string `json:"username,omitempty"`
	Locale   string `json:"locale,omitempty"`
	Email    string `json:"email,omitempty"`
}

// ChangePasswordRequest 改密请求。
type ChangePasswordRequest struct {
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

// Session 用户 session 信息。
type Session struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	IP         string `json:"ip,omitempty"`
	UserAgent  string `json:"user_agent,omitempty"`
	LastUsedAt int64  `json:"last_used_at"`
	ExpiresAt  int64  `json:"expires_at"`
	CreatedAt  int64  `json:"created_at"`
}

// CreateUserRequest admin 创建用户请求。
type CreateUserRequest struct {
	Username string   `json:"username"`
	Password string   `json:"password"`
	Role     UserRole `json:"role"`
	Email    string   `json:"email,omitempty"`
}

// UpdateUserRequest admin 修改用户请求。
type UpdateUserRequest struct {
	Username string   `json:"username,omitempty"`
	Role     UserRole `json:"role,omitempty"`
	IsActive *bool    `json:"is_active,omitempty"`
	Email    string   `json:"email,omitempty"`
}

// ResetPasswordResponse admin 重置密码响应。
type ResetPasswordResponse struct {
	NewPassword string `json:"new_password"`
}

// ---------------------------------------------------------------------------
// M-SUB：订阅 DTO
// ---------------------------------------------------------------------------

// Subscription 订阅信息。
type Subscription struct {
	ID             string     `json:"id"`
	UserID         string     `json:"user_id"`
	Name           string     `json:"name"`
	Type           SubType    `json:"type"`
	SourceURL      string     `json:"source_url,omitempty"`
	UA             string     `json:"ua,omitempty"`
	SyncInterval   int32      `json:"sync_interval"`
	LastSyncedAt   int64      `json:"last_synced_at,omitempty"`
	LastSyncStatus SyncStatus `json:"last_sync_status,omitempty"`
	LastSyncError  string     `json:"last_sync_error,omitempty"`
	ExpireAt       int64      `json:"expire_at,omitempty"`
	TrafficTotal   int64      `json:"traffic_total,omitempty"`
	TrafficUsed    int64      `json:"traffic_used,omitempty"`
	Tags           []string   `json:"tags"`
	Remark         string     `json:"remark,omitempty"`
	NodeCount      int32      `json:"node_count"`
	CreatedAt      int64      `json:"created_at"`
	UpdatedAt      int64      `json:"updated_at"`
}

// SubscriptionDetail 订阅详情（含节点列表）。
//
// 仅订阅详情接口（GET /api/subscriptions/:id）返回完整 share_token；列表接口
// （GET /api/subscriptions）不返回该字段，避免在多订阅页面无意中泄露 sub-store
// 兼容 URL 凭据（详见 docs/05-tech-lead-plan.md §1.3 裁决）。
type SubscriptionDetail struct {
	Subscription
	ShareToken       string            `json:"share_token,omitempty"`
	Nodes            []Node            `json:"nodes"`
	NodesTotal       int32             `json:"nodes_total"`
	PipelineBindings []PipelineBinding `json:"pipeline_bindings"`
}

// RotateShareTokenResponse 轮换 sub-store 兼容 token 响应。
//
// 由 POST /api/subscriptions/:id/rotate-share-token 返回新 share_token。
type RotateShareTokenResponse struct {
	ShareToken string `json:"share_token"`
}

// CreateSubscriptionRequest 创建订阅请求。
type CreateSubscriptionRequest struct {
	Name         string   `json:"name"`
	Type         SubType  `json:"type"`
	SourceURL    string   `json:"source_url,omitempty"`
	UA           string   `json:"ua,omitempty"`
	SyncInterval int32    `json:"sync_interval,omitempty"`
	Tags         []string `json:"tags,omitempty"`
	Remark       string   `json:"remark,omitempty"`
}

// UpdateSubscriptionRequest 修改订阅元数据请求。
type UpdateSubscriptionRequest struct {
	Name         string   `json:"name,omitempty"`
	SourceURL    string   `json:"source_url,omitempty"`
	UA           string   `json:"ua,omitempty"`
	SyncInterval int32    `json:"sync_interval,omitempty"`
	Tags         []string `json:"tags,omitempty"`
	Remark       string   `json:"remark,omitempty"`
}

// SyncResult 同步结果。
type SyncResult struct {
	SubscriptionID string `json:"subscription_id"`
	NodeCount      int32  `json:"node_count"`
	AddedCount     int32  `json:"added_count"`
	RemovedCount   int32  `json:"removed_count"`
	SyncedAt       int64  `json:"synced_at"`
}

// UpdatePipelineBindingsRequest 重置订阅绑定流水线请求。
type UpdatePipelineBindingsRequest struct {
	Bindings []PipelineBindingInput `json:"bindings"`
}

// PipelineBindingInput 流水线绑定输入。
type PipelineBindingInput struct {
	PipelineID string `json:"pipeline_id"`
	Position   int32  `json:"position"`
	Enabled    bool   `json:"enabled"`
}

// ---------------------------------------------------------------------------
// M-NODE：节点 DTO
// ---------------------------------------------------------------------------

// Node 节点信息。
type Node struct {
	ID            string       `json:"id"`
	SubscriptionID string      `json:"subscription_id"`
	RawURI        string       `json:"raw_uri"`
	Protocol      NodeProtocol `json:"protocol"`
	Server        string       `json:"server"`
	Port          int32        `json:"port"`
	Tag           string       `json:"tag"`
	Tags          []string     `json:"tags"`
	IsChainProxy  bool         `json:"is_chain_proxy"`
	ChainParentID string       `json:"chain_parent_id,omitempty"`
	ParsedConfig  any          `json:"parsed_config"`
	Position      int32        `json:"position"`
	CreatedAt     int64        `json:"created_at"`
	UpdatedAt     int64        `json:"updated_at"`
}

// NodeWithLatency 含 TCPing 结果的节点。
type NodeWithLatency struct {
	Node
	LatencyMs int32 `json:"latency_ms"` // -1 = 不可达
	Reachable bool  `json:"reachable"`
	TestedAt  int64 `json:"tested_at,omitempty"`
}

// AddNodeRequest 手动添加节点请求（URI 字符串）。
type AddNodeRequest struct {
	RawURI string `json:"raw_uri"`
}

// UpdateNodeRequest 修改节点请求。
type UpdateNodeRequest struct {
	Tags          []string `json:"tags,omitempty"`
	ChainParentID string   `json:"chain_parent_id,omitempty"`
}

// TCPingRequest 批量 TCPing 请求。
type TCPingRequest struct {
	NodeIDs     []string `json:"node_ids"`
	TimeoutMs   int32    `json:"timeout_ms,omitempty"`
	Concurrency int32    `json:"concurrency,omitempty"`
}

// TCPingResult 单个节点 TCPing 结果。
type TCPingResult struct {
	NodeID    string `json:"node_id"`
	LatencyMs int32  `json:"latency_ms"`
	Reachable bool   `json:"reachable"`
}

// TCPingResponse 批量 TCPing 响应。
type TCPingResponse struct {
	Results []TCPingResult `json:"results"`
}

// SetChainRequest 设置链式代理请求。
type SetChainRequest struct {
	ParentNodeID string `json:"parent_node_id"` // 空字符串表示取消
}

// ---------------------------------------------------------------------------
// M-PIPE：流水线 DTO
// ---------------------------------------------------------------------------

// Pipeline 流水线信息。
type Pipeline struct {
	ID            string `json:"id"`
	UserID        string `json:"user_id"`
	Name          string `json:"name"`
	YAMLContent   string `json:"yaml_content"`
	ASTJson       string `json:"ast_json"`
	Version       int32  `json:"version"`
	SchemaVersion string `json:"schema_version"`
	CreatedAt     int64  `json:"created_at"`
	UpdatedAt     int64  `json:"updated_at"`
}

// PipelineOperator 算子节点（用于 AST）。
type PipelineOperator struct {
	ID       string       `json:"id"`
	Type     OperatorType `json:"type"`
	Enabled  bool         `json:"enabled"`
	Params   any          `json:"params"`
	Position int32        `json:"position"`
}

// PipelineBinding 流水线绑定关系。
type PipelineBinding struct {
	SubscriptionID string `json:"subscription_id"`
	PipelineID     string `json:"pipeline_id"`
	Position       int32  `json:"position"`
	Enabled        bool   `json:"enabled"`
}

// FilterArgs filter 算子参数。
type FilterArgs struct {
	Expr string `json:"expr"`
}

// MapArgs map 算子参数。
type MapArgs struct {
	Field string `json:"field"`
	Value string `json:"value"`
}

// SortArgs sort 算子参数。
type SortArgs struct {
	Key   string `json:"key"`
	Order string `json:"order"` // "asc" | "desc"
}

// DedupeArgs dedupe 算子参数。
type DedupeArgs struct {
	Fields []string `json:"fields"`
}

// RegexRenameArgs regex_rename 算子参数。
type RegexRenameArgs struct {
	Pattern     string `json:"pattern"`
	Replacement string `json:"replacement"`
}

// OutputArgs output 算子参数。
type OutputArgs struct {
	Format   string `json:"format"`    // "clash" | "clash_meta" | "raw"
	MaxNodes int32  `json:"max_nodes,omitempty"`
}

// CreatePipelineRequest 创建流水线请求。
type CreatePipelineRequest struct {
	Name        string `json:"name"`
	YAMLContent string `json:"yaml_content"`
}

// UpdatePipelineRequest 保存流水线请求（整体替换）。
type UpdatePipelineRequest struct {
	Name        string `json:"name,omitempty"`
	YAMLContent string `json:"yaml_content"`
	ASTJson     string `json:"ast_json"`
	Version     int32  `json:"version"` // 乐观锁
}

// RunPipelineRequest Dry-run 请求。
type RunPipelineRequest struct {
	SubscriptionID string `json:"subscription_id"`
	Debug          bool   `json:"debug,omitempty"`
}

// OperatorStepResult 单个算子执行结果（调试用）。
type OperatorStepResult struct {
	Operator    string   `json:"operator"`
	InputCount  int32    `json:"input_count"`
	OutputCount int32    `json:"output_count"`
	Removed     []string `json:"removed"`
	Added       []string `json:"added"`
	Modified    []string `json:"modified"`
}

// RunPipelineResponse Dry-run 响应。
type RunPipelineResponse struct {
	TotalMs     int64                `json:"total_ms"`
	OutputCount int32                `json:"output_count"`
	Steps       []OperatorStepResult `json:"steps,omitempty"`
}

// YAMLToASTRequest YAML → AST 转换请求。
type YAMLToASTRequest struct {
	YAMLContent string `json:"yaml_content"`
}

// ASTToYAMLRequest AST → YAML 转换请求。
type ASTToYAMLRequest struct {
	ASTJson string `json:"ast_json"`
}

// OperatorSchema 算子 schema 描述。
type OperatorSchema struct {
	Type        OperatorType `json:"type"`
	DisplayName string       `json:"display_name"`
	Description string       `json:"description"`
	ParamsSchema any         `json:"params_schema"` // JSON Schema object
}

// ---------------------------------------------------------------------------
// M-RULE：规则 DTO
// ---------------------------------------------------------------------------

// CustomRule 自定义规则。
type CustomRule struct {
	ID        string   `json:"id"`
	UserID    string   `json:"user_id"`
	Name      string   `json:"name"`
	Type      RuleType `json:"type"`
	Mode      RuleMode `json:"mode"`
	Content   string   `json:"content"`
	Enabled   bool     `json:"enabled"`
	Sort      int32    `json:"sort"`
	CreatedAt int64    `json:"created_at"`
	UpdatedAt int64    `json:"updated_at"`
}

// CreateRuleRequest 创建规则请求。
type CreateRuleRequest struct {
	Name    string   `json:"name"`
	Type    RuleType `json:"type"`
	Mode    RuleMode `json:"mode"`
	Content string   `json:"content"`
	Enabled bool     `json:"enabled"`
	Sort    int32    `json:"sort,omitempty"`
}

// UpdateRuleRequest 修改规则请求。
type UpdateRuleRequest struct {
	Name    string   `json:"name,omitempty"`
	Mode    RuleMode `json:"mode,omitempty"`
	Content string   `json:"content,omitempty"`
	Enabled *bool    `json:"enabled,omitempty"`
}

// UpdateRuleOrderRequest 批量改 sort 请求。
type UpdateRuleOrderRequest struct {
	Orders []RuleOrder `json:"orders"`
}

// RuleOrder 规则排序项。
type RuleOrder struct {
	ID   string `json:"id"`
	Sort int32  `json:"sort"`
}

// RuleTemplate 规则预设模板。
type RuleTemplate struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Content     string `json:"content"`
}

// ---------------------------------------------------------------------------
// M-SCRIPT：脚本 DTO
// ---------------------------------------------------------------------------

// Script 脚本信息。
type Script struct {
	ID        string   `json:"id"`
	UserID    string   `json:"user_id"`
	Name      string   `json:"name"`
	Hook      HookType `json:"hook"`
	Code      string   `json:"code"`
	Enabled   bool     `json:"enabled"`
	LastRunAt int64    `json:"last_run_at,omitempty"`
	LastError string   `json:"last_error,omitempty"`
	CreatedAt int64    `json:"created_at"`
	UpdatedAt int64    `json:"updated_at"`
}

// CreateScriptRequest 创建脚本请求。
type CreateScriptRequest struct {
	Name    string   `json:"name"`
	Hook    HookType `json:"hook"`
	Code    string   `json:"code"`
	Enabled bool     `json:"enabled"`
}

// UpdateScriptRequest 修改脚本请求。
type UpdateScriptRequest struct {
	Name    string `json:"name,omitempty"`
	Code    string `json:"code,omitempty"`
	Enabled *bool  `json:"enabled,omitempty"`
}

// ScriptTestRequest 脚本 dry-run 请求。
type ScriptTestRequest struct {
	SampleNodes string `json:"sample_nodes"` // JSON array string
}

// ScriptTestResponse 脚本 dry-run 响应。
type ScriptTestResponse struct {
	OutputNodes string `json:"output_nodes"` // JSON array string
	DurationMs  int64  `json:"duration_ms"`
	Error       string `json:"error,omitempty"`
}

// ScriptLog 脚本错误日志条目。
type ScriptLog struct {
	Timestamp int64  `json:"timestamp"`
	Level     string `json:"level"`
	Message   string `json:"message"`
	Error     string `json:"error,omitempty"`
}

// ---------------------------------------------------------------------------
// M-AGENT：探针 agent DTO
// ---------------------------------------------------------------------------

// Agent agent 信息。
type Agent struct {
	ID         string      `json:"id"`
	UserID     string      `json:"user_id"`
	Name       string      `json:"name"`
	Kind       AgentKind   `json:"kind"`
	Version    string      `json:"version,omitempty"`
	OS         string      `json:"os,omitempty"`
	Arch       string      `json:"arch,omitempty"`
	PublicIP   string      `json:"public_ip,omitempty"`
	LastSeenAt int64       `json:"last_seen_at,omitempty"`
	Status     AgentStatus `json:"status"`
	CreatedAt  int64       `json:"created_at"`
	UpdatedAt  int64       `json:"updated_at"`
}

// AgentCreateResponse 创建 agent 时的响应（含一次性 token）。
type AgentCreateResponse struct {
	Agent
	Token          string `json:"token"`           // 明文 token，仅此一次
	InstallCommand string `json:"install_command"` // 一键安装命令
}

// AgentMetric 实时指标快照（来自 agent_records）。
type AgentMetric struct {
	AgentID      string  `json:"agent_id"`
	RecordedAt   int64   `json:"recorded_at"`
	CPUPercent   float64 `json:"cpu_percent"`
	MemUsed      int64   `json:"mem_used"`
	MemTotal     int64   `json:"mem_total"`
	SwapUsed     int64   `json:"swap_used"`
	SwapTotal    int64   `json:"swap_total"`
	DiskUsed     int64   `json:"disk_used"`
	DiskTotal    int64   `json:"disk_total"`
	NetIn        int64   `json:"net_in"`
	NetOut       int64   `json:"net_out"`
	NetInSpeed   int64   `json:"net_in_speed"`
	NetOutSpeed  int64   `json:"net_out_speed"`
	Load1        float64 `json:"load1"`
	Load5        float64 `json:"load5"`
	Load15       float64 `json:"load15"`
	ConnTCP      int32   `json:"conn_tcp"`
	ConnUDP      int32   `json:"conn_udp"`
	Uptime       int64   `json:"uptime"`
	ProcessCount int32   `json:"process_count,omitempty"`
}

// CreateAgentRequest 创建 agent 请求。
type CreateAgentRequest struct {
	Name string `json:"name"`
}

// UpdateAgentRequest 修改 agent 请求。
type UpdateAgentRequest struct {
	Name string `json:"name,omitempty"`
}

// RotateTokenResponse 轮换 token 响应。
type RotateTokenResponse struct {
	Token string `json:"token"`
}

// ---------------------------------------------------------------------------
// M-TRAFFIC：流量 DTO
// ---------------------------------------------------------------------------

// TrafficRecord 日聚合流量记录。
type TrafficRecord struct {
	Date       string `json:"date"`       // YYYY-MM-DD
	UserID     string `json:"user_id"`
	AgentID    string `json:"agent_id,omitempty"`
	TotalLimit int64  `json:"total_limit,omitempty"`
	TotalUsed  int64  `json:"total_used"`
	TotalIn    int64  `json:"total_in"`
	TotalOut   int64  `json:"total_out"`
}

// AgentTrafficSummary 单 agent 流量概览。
type AgentTrafficSummary struct {
	AgentID    string `json:"agent_id"`
	AgentName  string `json:"agent_name"`
	TotalIn    int64  `json:"total_in"`
	TotalOut   int64  `json:"total_out"`
	TotalUsed  int64  `json:"total_used"`
}

// TrafficSummary 当月流量汇总。
type TrafficSummary struct {
	UserID        string                `json:"user_id"`
	PeriodStart   string                `json:"period_start"` // YYYY-MM-DD
	PeriodEnd     string                `json:"period_end"`
	TotalLimit    int64                 `json:"total_limit,omitempty"`
	TotalUsed     int64                 `json:"total_used"`
	TotalIn       int64                 `json:"total_in"`
	TotalOut      int64                 `json:"total_out"`
	UsagePercent  float64               `json:"usage_percent"`
	Agents        []AgentTrafficSummary `json:"agents"`
}

// TrafficChartPoint 图表数据点。
type TrafficChartPoint struct {
	Date     string  `json:"date"`
	TotalIn  int64   `json:"total_in"`
	TotalOut int64   `json:"total_out"`
	AgentID  string  `json:"agent_id,omitempty"`
}

// TrafficThresholdRequest 设置流量阈值请求。
type TrafficThresholdRequest struct {
	ThresholdPercent int32 `json:"threshold_percent"` // 0-100
	TotalLimit       int64 `json:"total_limit,omitempty"`
}

// ---------------------------------------------------------------------------
// M-NOTIFY：通知 DTO
// ---------------------------------------------------------------------------

// NotificationChannel 通知通道。
type NotificationChannel struct {
	ID         string      `json:"id"`
	UserID     string      `json:"user_id"`
	Kind       ChannelKind `json:"kind"`
	Name       string      `json:"name"`
	Config     any         `json:"config"` // 对应各渠道 Config struct
	Template   string      `json:"template,omitempty"`
	EventTypes []EventType `json:"event_types"`
	Enabled    bool        `json:"enabled"`
	CreatedAt  int64       `json:"created_at"`
	UpdatedAt  int64       `json:"updated_at"`
}

// 渠道专属配置 struct（由 config 字段携带）

// TelegramConfig Telegram Bot 渠道配置。
type TelegramConfig struct {
	BotToken  string `json:"bot_token"`
	ChatID    string `json:"chat_id"`
	ParseMode string `json:"parse_mode,omitempty"` // "HTML" | "Markdown"
}

// DiscordConfig Discord Webhook 渠道配置。
type DiscordConfig struct {
	WebhookURL string `json:"webhook_url"`
	Username   string `json:"username,omitempty"`
}

// SlackConfig Slack Incoming Webhook 渠道配置。
type SlackConfig struct {
	WebhookURL string `json:"webhook_url"`
	Channel    string `json:"channel,omitempty"`
}

// EmailConfig SMTP 邮件渠道配置。
type EmailConfig struct {
	SMTPHost     string   `json:"smtp_host"`
	SMTPPort     int32    `json:"smtp_port"`
	SMTPUser     string   `json:"smtp_user"`
	SMTPPassword string   `json:"smtp_password"`
	SMTPTLS      bool     `json:"smtp_tls"`
	From         string   `json:"from"`
	To           []string `json:"to"`
}

// BarkConfig Bark 推送渠道配置。
type BarkConfig struct {
	DeviceKey string `json:"device_key"`
	ServerURL string `json:"server_url,omitempty"`
}

// GotifyConfig Gotify 渠道配置。
type GotifyConfig struct {
	ServerURL string `json:"server_url"`
	AppToken  string `json:"app_token"`
}

// WebhookConfig 通用 Webhook 渠道配置。
type WebhookConfig struct {
	URL     string            `json:"url"`
	Method  string            `json:"method,omitempty"` // "POST" | "GET"
	Headers map[string]string `json:"headers,omitempty"`
}

// ServerChanConfig Server酱渠道配置。
type ServerChanConfig struct {
	SendKey string `json:"send_key"`
}

// PushDeerConfig PushDeer 渠道配置。
type PushDeerConfig struct {
	PushKey   string `json:"push_key"`
	ServerURL string `json:"server_url,omitempty"`
}

// IFTTTConfig IFTTT Webhook 渠道配置。
type IFTTTConfig struct {
	WebhookKey string `json:"webhook_key"`
	EventName  string `json:"event_name"`
}

// CreateChannelRequest 创建通道请求。
type CreateChannelRequest struct {
	Kind       ChannelKind `json:"kind"`
	Name       string      `json:"name"`
	Config     any         `json:"config"`
	Template   string      `json:"template,omitempty"`
	EventTypes []EventType `json:"event_types"`
	Enabled    bool        `json:"enabled"`
}

// UpdateChannelRequest 修改通道请求。
type UpdateChannelRequest struct {
	Name       string      `json:"name,omitempty"`
	Config     any         `json:"config,omitempty"`
	Template   string      `json:"template,omitempty"`
	EventTypes []EventType `json:"event_types,omitempty"`
	Enabled    *bool       `json:"enabled,omitempty"`
}

// ChannelKindSchema 通道类型 schema 描述。
type ChannelKindSchema struct {
	Kind        ChannelKind `json:"kind"`
	DisplayName string      `json:"display_name"`
	ConfigSchema any        `json:"config_schema"` // JSON Schema
}

// NotificationEvent 通知投递记录。
type NotificationEvent struct {
	ID        int64       `json:"id"`
	UserID    string      `json:"user_id"`
	ChannelID string      `json:"channel_id,omitempty"`
	EventType EventType   `json:"event_type"`
	Payload   any         `json:"payload"`
	Status    EventStatus `json:"status"`
	SentAt    int64       `json:"sent_at,omitempty"`
	Error     string      `json:"error,omitempty"`
	CreatedAt int64       `json:"created_at"`
}

// ---------------------------------------------------------------------------
// M-OPS：短链 / OTA / 设置 / 审计 DTO
// ---------------------------------------------------------------------------

// ShortLink 短链信息。
type ShortLink struct {
	FileCode  string `json:"file_code"`
	UserCode  string `json:"user_code"`
	UserID    string `json:"user_id"`
	TargetURL string `json:"target_url"`
	ShortURL  string `json:"short_url"`
	ExpiresAt int64  `json:"expires_at,omitempty"`
	CreatedAt int64  `json:"created_at"`
}

// CreateShortLinkRequest 创建短链请求。
type CreateShortLinkRequest struct {
	TargetURL string `json:"target_url"`
	ExpiresAt int64  `json:"expires_at,omitempty"` // 0=永久
}

// OTAReleaseInfo OTA 检查结果。
type OTAReleaseInfo struct {
	LatestVersion  string `json:"latest_version"`
	CurrentVersion string `json:"current_version"`
	HasUpdate      bool   `json:"has_update"`
	ReleaseURL     string `json:"release_url"`
	Changelog      string `json:"changelog,omitempty"`
	SHA256         string `json:"sha256"`
	PublishedAt    int64  `json:"published_at"`
}

// OTAHistoryItem OTA 升级历史条目。
type OTAHistoryItem struct {
	Version   string `json:"version"`
	Status    string `json:"status"` // "success" | "failed"
	AppliedAt int64  `json:"applied_at"`
	Error     string `json:"error,omitempty"`
}

// AuditLog 审计日志条目。
type AuditLog struct {
	ID           int64  `json:"id"`
	UserID       string `json:"user_id,omitempty"`
	Action       string `json:"action"`
	ResourceType string `json:"resource_type,omitempty"`
	ResourceID   string `json:"resource_id,omitempty"`
	IP           string `json:"ip,omitempty"`
	UserAgent    string `json:"user_agent,omitempty"`
	Payload      any    `json:"payload,omitempty"`
	Success      bool   `json:"success"`
	CreatedAt    int64  `json:"created_at"`
}

// SystemSetting 系统设置 k/v 键值对。
type SystemSetting struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt int64  `json:"updated_at"`
}

// SystemSettingsMap 系统设置映射（批量读取时使用）。
type SystemSettingsMap struct {
	SilentModeEnabled       bool   `json:"silent_mode_enabled"`
	SilentModePrefix        string `json:"silent_mode_prefix"`
	SessionTTLSeconds       int64  `json:"session_ttl_seconds"`
	MonthlyResetDay         int32  `json:"monthly_reset_day"`
	OTACheckInterval        int32  `json:"ota_check_interval"`
	AgentHeartbeatInterval  int32  `json:"agent_heartbeat_interval"`
	NotificationDebounce    int32  `json:"notification_debounce"`
}

// UpdateSettingsRequest 修改系统设置请求（部分更新）。
type UpdateSettingsRequest struct {
	SilentModeEnabled      *bool  `json:"silent_mode_enabled,omitempty"`
	SessionTTLSeconds      int64  `json:"session_ttl_seconds,omitempty"`
	MonthlyResetDay        int32  `json:"monthly_reset_day,omitempty"`
	OTACheckInterval       int32  `json:"ota_check_interval,omitempty"`
	AgentHeartbeatInterval int32  `json:"agent_heartbeat_interval,omitempty"`
	NotificationDebounce   int32  `json:"notification_debounce,omitempty"`
}

// SilentModeRequest 开关静默模式 / 轮换前缀请求。
type SilentModeRequest struct {
	Enabled  *bool `json:"enabled,omitempty"`
	Rotate   bool  `json:"rotate,omitempty"` // 是否立即轮换前缀
}

// SilentModeResponse 静默模式操作响应（含新前缀）。
type SilentModeResponse struct {
	Enabled bool   `json:"enabled"`
	Prefix  string `json:"prefix"`
	LoginURL string `json:"login_url"`
}

// SSEEvent 前端 SSE 实时事件（通过 /api/notify/stream 推送）。
type SSEEvent struct {
	Kind    string `json:"kind"` // "agent_status" | "notification_event" | "subscription_sync" | "system"
	Payload any    `json:"payload"`
}
