// Code generated by api-contract. DO NOT EDIT.
// 修改本文件请同步更新：
//   - docs/04-api-contract.md
//   - web/src/types/wsproto.ts
//   - pkg/agentlib/protocol.go
package types

// ---------------------------------------------------------------------------
// WebSocket 消息类型常量
// ---------------------------------------------------------------------------

// WsMessageType WebSocket 消息 type 字段枚举。
type WsMessageType string

const (
	WsMsgHello     WsMessageType = "hello"
	WsMsgHelloAck  WsMessageType = "hello_ack"
	WsMsgHeartbeat WsMessageType = "heartbeat"
	WsMsgMetrics   WsMessageType = "metrics"
	WsMsgCmd       WsMessageType = "cmd"
	WsMsgCmdAck    WsMessageType = "cmd_ack"
	WsMsgBye       WsMessageType = "bye"
)

// WsCmdType agent 命令类型。
type WsCmdType string

const (
	CmdRestart             WsCmdType = "restart"
	CmdRefreshSubscription WsCmdType = "refresh_subscription"
	CmdCollectNow          WsCmdType = "collect_now"  // P2 预留
	CmdShutdown            WsCmdType = "shutdown"     // P2 预留
)

// ---------------------------------------------------------------------------
// 通用信封（所有 WS 消息共用）
// ---------------------------------------------------------------------------

// WsEnvelope 通用信封。
// type 字段决定 payload 的具体类型，接收方通过 type switch 解包。
type WsEnvelope struct {
	Type    WsMessageType `json:"type"`
	ID      string        `json:"id"`      // 消息 UUID（客户端生成）
	Payload []byte        `json:"payload"` // json.RawMessage 编码的具体 payload
	TS      int64         `json:"ts"`      // unix ms
}

// ---------------------------------------------------------------------------
// hub ↔ agent 协议 payload（镜像 pkg/agentlib/protocol.go，Hub 端定义）
// ---------------------------------------------------------------------------

// WsHelloPayload agent → hub 握手消息 payload。
type WsHelloPayload struct {
	AgentID      string   `json:"agent_id"`
	Token        string   `json:"token"`
	OS           string   `json:"os"`
	Arch         string   `json:"arch"`
	Version      string   `json:"version"`
	Kind         string   `json:"kind"`         // "native" | "nezha_compat"
	Capabilities []string `json:"capabilities"` // ["metrics", "restart", ...]
}

// WsHelloAckPayload hub → agent 握手响应 payload。
type WsHelloAckPayload struct {
	OK                bool   `json:"ok"`
	HeartbeatInterval int32  `json:"heartbeat_interval"` // 秒
	HubVersion        string `json:"hub_version"`
}

// WsHeartbeatPayload agent → hub 心跳 payload（轻量，指标通过 metrics 消息分开发送）。
type WsHeartbeatPayload struct {
	AgentID string `json:"agent_id"`
	Uptime  int64  `json:"uptime"` // 秒
}

// WsMetricsPayload agent → hub 指标上报 payload。
// 字段与 AgentMetric 保持一致（协议向后兼容：新增字段可选，不可删除已有字段）。
type WsMetricsPayload struct {
	AgentID      string  `json:"agent_id"`
	CPUPercent   float64 `json:"cpu_percent"`
	MemUsed      int64   `json:"mem_used"`
	MemTotal     int64   `json:"mem_total"`
	SwapUsed     int64   `json:"swap_used"`
	SwapTotal    int64   `json:"swap_total"`
	DiskUsed     int64   `json:"disk_used"`
	DiskTotal    int64   `json:"disk_total"`
	NetIn        int64   `json:"net_in"`
	NetOut       int64   `json:"net_out"`
	NetInSpeed   int64   `json:"net_in_speed"`
	NetOutSpeed  int64   `json:"net_out_speed"`
	Load1        float64 `json:"load1"`
	Load5        float64 `json:"load5"`
	Load15       float64 `json:"load15"`
	ConnTCP      int32   `json:"conn_tcp"`
	ConnUDP      int32   `json:"conn_udp"`
	Uptime       int64   `json:"uptime"`
	ProcessCount int32   `json:"process_count,omitempty"`
}

// WsCmdPayload hub → agent 命令下发 payload。
type WsCmdPayload struct {
	Cmd  WsCmdType         `json:"cmd"`
	Args map[string]string `json:"args,omitempty"`
}

// WsCmdAckPayload agent → hub 命令响应 payload。
type WsCmdAckPayload struct {
	CmdID string `json:"cmd_id"` // 对应 WsEnvelope.ID
	OK    bool   `json:"ok"`
	Error string `json:"error,omitempty"`
}

// WsByePayload 断开通知 payload（任意方向）。
type WsByePayload struct {
	Reason string `json:"reason,omitempty"` // 如 "token_rotated" / "server_shutdown"
}

// ---------------------------------------------------------------------------
// 前端 SSE 事件 payload 类型（hub → browser，通过 /api/notify/stream）
// ---------------------------------------------------------------------------

// SSEAgentStatusPayload agent 状态变化事件 payload。
type SSEAgentStatusPayload struct {
	AgentID string `json:"agent_id"`
	Status  string `json:"status"` // "online" | "offline" | "degraded"
	TS      int64  `json:"ts"`
}

// SSENotificationEventPayload 通知投递状态事件 payload。
type SSENotificationEventPayload struct {
	EventType string `json:"event_type"`
	ChannelID string `json:"channel_id,omitempty"`
	Status    string `json:"status"` // "sent" | "failed"
	TS        int64  `json:"ts"`
}

// SSESubscriptionSyncPayload 订阅同步进度事件 payload。
type SSESubscriptionSyncPayload struct {
	SubscriptionID string `json:"subscription_id"`
	Status         string `json:"status"` // "ok" | "error" | "pending"
	NodeCount      int32  `json:"node_count,omitempty"`
	Error          string `json:"error,omitempty"`
	TS             int64  `json:"ts"`
}

// SSESystemPayload 系统级事件 payload（如 OTA 有新版本）。
type SSESystemPayload struct {
	Kind    string `json:"kind"`    // "ota_available" | "settings_changed"
	Version string `json:"version,omitempty"`
	TS      int64  `json:"ts"`
}
