/**
 * Code generated by api-contract. DO NOT EDIT.
 * 修改本文件请同步更新：
 *   - docs/04-api-contract.md
 *   - internal/types/wsproto.go
 *   - pkg/agentlib/protocol.go
 */

// ---------------------------------------------------------------------------
// 消息类型常量
// ---------------------------------------------------------------------------

export type WsMessageType =
  | "hello"
  | "hello_ack"
  | "heartbeat"
  | "metrics"
  | "cmd"
  | "cmd_ack"
  | "bye";

export type WsCmdType =
  | "restart"
  | "refresh_subscription"
  | "collect_now"   // P2 预留
  | "shutdown";     // P2 预留

export type AgentKindWs = "native" | "nezha_compat";

// ---------------------------------------------------------------------------
// 通用信封
// ---------------------------------------------------------------------------

/**
 * WsEnvelope 所有 WebSocket 消息的外层信封。
 *
 * 泛型参数 T 对应 type 字段所指定的具体 payload 类型。
 * 接收方应先检查 type 字段，再将 payload 强转为对应类型。
 *
 * 完整 discriminated union 见文件末尾 WsMessage。
 */
export interface WsEnvelope<T = unknown> {
  type: WsMessageType;
  id: string;       // 消息唯一 UUID
  payload: T;
  ts: number;       // unix ms
}

// ---------------------------------------------------------------------------
// hub ↔ agent 协议 payload
// ---------------------------------------------------------------------------

/** HelloPayload agent → hub 握手 payload。 */
export interface HelloPayload {
  agent_id: string;
  token: string;
  os: string;
  arch: string;
  version: string;
  kind: AgentKindWs;
  capabilities: string[]; // ["metrics", "restart", ...]
}

/** HelloAckPayload hub → agent 握手响应 payload。 */
export interface HelloAckPayload {
  ok: boolean;
  heartbeat_interval: number; // 秒
  hub_version: string;
}

/** HeartbeatPayload agent → hub 轻量心跳 payload。 */
export interface HeartbeatPayload {
  agent_id: string;
  uptime: number; // 秒
}

/** MetricsPayload agent → hub 指标上报 payload。 */
export interface MetricsPayload {
  agent_id: string;
  cpu_percent: number;
  mem_used: number;
  mem_total: number;
  swap_used: number;
  swap_total: number;
  disk_used: number;
  disk_total: number;
  net_in: number;
  net_out: number;
  net_in_speed: number;
  net_out_speed: number;
  load1: number;
  load5: number;
  load15: number;
  conn_tcp: number;
  conn_udp: number;
  uptime: number;
  process_count?: number; // v1.1 新增，可选
}

/** CmdPayload hub → agent 命令下发 payload。 */
export interface CmdPayload {
  cmd: WsCmdType;
  args?: Record<string, string>;
}

/** CmdAckPayload agent → hub 命令执行结果 payload。 */
export interface CmdAckPayload {
  cmd_id: string; // 对应 WsEnvelope.id
  ok: boolean;
  error?: string;
}

/** ByePayload 断开通知 payload（任意方向）。 */
export interface ByePayload {
  reason?: string; // "token_rotated" | "server_shutdown" | "idle_timeout"
}

// ---------------------------------------------------------------------------
// Discriminated Union（前端 type switch 用）
// ---------------------------------------------------------------------------

export type HelloMsg = WsEnvelope<HelloPayload> & { type: "hello" };
export type HelloAckMsg = WsEnvelope<HelloAckPayload> & { type: "hello_ack" };
export type HeartbeatMsg = WsEnvelope<HeartbeatPayload> & { type: "heartbeat" };
export type MetricsMsg = WsEnvelope<MetricsPayload> & { type: "metrics" };
export type CmdMsg = WsEnvelope<CmdPayload> & { type: "cmd" };
export type CmdAckMsg = WsEnvelope<CmdAckPayload> & { type: "cmd_ack" };
export type ByeMsg = WsEnvelope<ByePayload> & { type: "bye" };

/**
 * WsMessage 所有 WebSocket 消息的 discriminated union。
 *
 * 用法（前端处理 agent WS 消息时）：
 * ```ts
 * function handleMessage(msg: WsMessage) {
 *   switch (msg.type) {
 *     case "hello":     // msg.payload is HelloPayload
 *     case "metrics":   // msg.payload is MetricsPayload
 *     ...
 *   }
 * }
 * ```
 */
export type WsMessage =
  | HelloMsg
  | HelloAckMsg
  | HeartbeatMsg
  | MetricsMsg
  | CmdMsg
  | CmdAckMsg
  | ByeMsg;

// ---------------------------------------------------------------------------
// 前端 SSE 事件类型（通过 /api/notify/stream 推送）
// ---------------------------------------------------------------------------

export type SSEEventKind =
  | "agent_status"
  | "notification_event"
  | "subscription_sync"
  | "system";

/** SSEAgentStatusPayload agent 状态变化事件。 */
export interface SSEAgentStatusPayload {
  agent_id: string;
  status: "online" | "offline" | "degraded";
  ts: number;
}

/** SSENotificationEventPayload 通知投递状态事件。 */
export interface SSENotificationEventPayload {
  event_type: string;
  channel_id?: string;
  status: "sent" | "failed";
  ts: number;
}

/** SSESubscriptionSyncPayload 订阅同步进度事件。 */
export interface SSESubscriptionSyncPayload {
  subscription_id: string;
  status: "ok" | "error" | "pending";
  node_count?: number;
  error?: string;
  ts: number;
}

/** SSESystemPayload 系统级事件（OTA 新版本/设置变更）。 */
export interface SSESystemPayload {
  kind: "ota_available" | "settings_changed";
  version?: string;
  ts: number;
}

export interface SSEAgentStatusEvent {
  kind: "agent_status";
  payload: SSEAgentStatusPayload;
}

export interface SSENotificationEvent {
  kind: "notification_event";
  payload: SSENotificationEventPayload;
}

export interface SSESubscriptionSyncEvent {
  kind: "subscription_sync";
  payload: SSESubscriptionSyncPayload;
}

export interface SSESystemEvent {
  kind: "system";
  payload: SSESystemPayload;
}

/**
 * SSEEvent 前端从 /api/notify/stream 收到的事件 discriminated union。
 *
 * 用法（在 useEventStream hook 中）：
 * ```ts
 * function handleSSE(event: SSEEvent) {
 *   switch (event.kind) {
 *     case "agent_status":    // event.payload is SSEAgentStatusPayload
 *     case "subscription_sync": // ...
 *   }
 * }
 * ```
 */
export type SSEEvent =
  | SSEAgentStatusEvent
  | SSENotificationEvent
  | SSESubscriptionSyncEvent
  | SSESystemEvent;
