/**
 * Code generated by api-contract. DO NOT EDIT.
 * 修改本文件请同步更新：
 *   - docs/04-api-contract.md
 *   - internal/types/api.go
 */

// ---------------------------------------------------------------------------
// 通用响应包装
// ---------------------------------------------------------------------------

export interface APIResponse<T = unknown> {
  code?: string;
  data?: T;
  message?: string;
  details?: unknown;
  request_id?: string;
}

export interface PagedResponse<T> {
  items: T[];
  total: number;
  page: number;
  page_size: number;
}

// ---------------------------------------------------------------------------
// 枚举类型
// ---------------------------------------------------------------------------

export type UserRole = "admin" | "user";

export type SubType = "url" | "upload" | "manual";

export type SyncStatus = "ok" | "error" | "pending";

export type NodeProtocol =
  | "vmess"
  | "vless"
  | "ss"
  | "ssr"
  | "trojan"
  | "hysteria"
  | "hysteria2"
  | "tuic"
  | "wireguard"
  | "anytls"
  | "socks5"
  | "naive";

export type OperatorType =
  | "filter"
  | "map"
  | "sort"
  | "dedupe"
  | "regex_rename"
  | "output";

export type RuleType = "dns" | "rules" | "rule-providers";

export type RuleMode = "replace" | "prepend" | "append";

export type HookType = "pre_save_nodes" | "post_fetch";

export type AgentKind = "native" | "nezha_compat";

export type AgentStatus = "online" | "offline" | "degraded";

export type ChannelKind =
  | "telegram"
  | "discord"
  | "slack"
  | "email"
  | "bark"
  | "gotify"
  | "webhook"
  | "serverchan"
  | "pushdeer"
  | "ifttt";

export type EventType =
  | "node_offline"
  | "traffic_threshold"
  | "subscription_sync_failed"
  | "backup_completed"
  | "login_anomaly"
  | "ota_available"
  | "script_alert"
  | "vps_expiry";

export type EventStatus = "pending" | "sent" | "failed" | "skipped_dedupe";

// ---------------------------------------------------------------------------
// 错误码
// ---------------------------------------------------------------------------

export type ErrorCode =
  // AUTH
  | "ERR_AUTH_INVALID_PASSWORD"
  | "ERR_AUTH_USER_INACTIVE"
  | "ERR_AUTH_TOTP_REQUIRED"
  | "ERR_AUTH_TOTP_INVALID"
  | "ERR_AUTH_TOTP_EXPIRED"
  | "ERR_AUTH_RECOVERY_CODE_INVALID"
  | "ERR_AUTH_RECOVERY_CODE_EXHAUSTED"
  | "ERR_AUTH_TOKEN_INVALID"
  | "ERR_AUTH_TOKEN_EXPIRED"
  | "ERR_AUTH_RATE_LIMITED"
  | "ERR_AUTH_BRUTE_FORCE_BLOCKED"
  | "ERR_AUTH_FORBIDDEN"
  // VALIDATION
  | "ERR_VALIDATION_REQUIRED_FIELD"
  | "ERR_VALIDATION_INVALID_FORMAT"
  | "ERR_VALIDATION_OUT_OF_RANGE"
  | "ERR_VALIDATION_REGEX_COMPILE"
  | "ERR_VALIDATION_YAML_PARSE"
  | "ERR_VALIDATION_SCHEMA_MISMATCH"
  // NOT_FOUND
  | "ERR_NOT_FOUND_USER"
  | "ERR_NOT_FOUND_SUBSCRIPTION"
  | "ERR_NOT_FOUND_NODE"
  | "ERR_NOT_FOUND_PIPELINE"
  | "ERR_NOT_FOUND_RULE"
  | "ERR_NOT_FOUND_SCRIPT"
  | "ERR_NOT_FOUND_AGENT"
  | "ERR_NOT_FOUND_CHANNEL"
  // CONFLICT
  | "ERR_CONFLICT_USERNAME"
  | "ERR_CONFLICT_PIPELINE_VERSION"
  | "ERR_CONFLICT_LAST_ADMIN"
  // PIPELINE
  | "ERR_PIPELINE_OPERATOR_UNKNOWN"
  | "ERR_PIPELINE_OPERATOR_PARAMS"
  | "ERR_PIPELINE_RUN_TIMEOUT"
  // SCRIPT
  | "ERR_SCRIPT_TIMEOUT"
  | "ERR_SCRIPT_SANDBOX_VIOLATION"
  | "ERR_SCRIPT_RUNTIME_ERROR"
  // AGENT
  | "ERR_AGENT_TOKEN_INVALID"
  | "ERR_AGENT_OFFLINE"
  | "ERR_AGENT_COMMAND_TIMEOUT"
  // INTERNAL
  | "ERR_INTERNAL_DATABASE"
  | "ERR_INTERNAL_UNKNOWN";

// ---------------------------------------------------------------------------
// M-USER：用户与认证 DTO
// ---------------------------------------------------------------------------

export interface User {
  id: string;
  username: string;
  role: UserRole;
  is_active: boolean;
  email?: string;
  locale: string;
  totp_enabled: boolean;
  created_at: number;
  updated_at: number;
}

export interface UserPublicProfile {
  id: string;
  username: string;
  role: UserRole;
  email?: string;
  locale: string;
  totp_enabled: boolean;
  created_at: number;
}

export interface LoginRequest {
  username: string;
  password: string;
}

export interface LoginResponse {
  access_token: string;
  expires_at: number;
  user: UserPublicProfile;
}

export interface PendingTOTPResponse {
  pending_token: string;
  expires_in: number;
  totp_required: boolean;
}

export interface VerifyTOTPRequest {
  pending_token: string;
  code: string;
}

export interface VerifyRecoveryRequest {
  pending_token: string;
  code: string;
}

export interface TOTPSetupResponse {
  secret: string;
  otpauth_uri: string;
  qr_code_url: string;
}

export interface EnableTOTPRequest {
  code: string;
}

export interface EnableTOTPResponse {
  backup_codes: string[];
}

export interface DisableTOTPRequest {
  code: string;
  password: string;
}

export interface UpdateMeRequest {
  username?: string;
  locale?: string;
  email?: string;
}

export interface ChangePasswordRequest {
  old_password: string;
  new_password: string;
}

export interface Session {
  id: string;
  user_id: string;
  ip?: string;
  user_agent?: string;
  last_used_at: number;
  expires_at: number;
  created_at: number;
}

export interface CreateUserRequest {
  username: string;
  password: string;
  role: UserRole;
  email?: string;
}

export interface UpdateUserRequest {
  username?: string;
  role?: UserRole;
  is_active?: boolean;
  email?: string;
}

export interface ResetPasswordResponse {
  new_password: string;
}

// ---------------------------------------------------------------------------
// M-SUB：订阅 DTO
// ---------------------------------------------------------------------------

export interface Subscription {
  id: string;
  user_id: string;
  name: string;
  type: SubType;
  source_url?: string;
  ua?: string;
  sync_interval: number;
  last_synced_at?: number;
  last_sync_status?: SyncStatus;
  last_sync_error?: string;
  expire_at?: number;
  traffic_total?: number;
  traffic_used?: number;
  tags: string[];
  remark?: string;
  node_count: number;
  created_at: number;
  updated_at: number;
}

export interface PipelineBinding {
  subscription_id: string;
  pipeline_id: string;
  position: number;
  enabled: boolean;
}

export interface SubscriptionDetail extends Subscription {
  nodes: Node[];
  nodes_total: number;
  pipeline_bindings: PipelineBinding[];
  /** Present only on owner / admin reads (matches internal/types/api.go §SubscriptionDetail). */
  share_token?: string;
}

export interface RotateShareTokenResponse {
  share_token: string;
}

/**
 * Subscription download target query parameter.
 *
 * Matches the values accepted by the backend ProducerFactory in
 * `internal/substore/producer_factory.go`. Use this enum when constructing
 * download URLs so the UI stays in lockstep with the server-side router.
 */
export type ClientTarget =
  | "clash"
  | "clashmeta"
  | "clash-verge"
  | "clash-verge-rev"
  | "mihomo"
  | "stash"
  | "openclash"
  | "singbox"
  | "sing-box"
  | "surge"
  | "surge-mac"
  | "surge-ios"
  | "v2ray"
  | "v2rayn"
  | "v2rayng"
  | "shadowrocket"
  | "qx"
  | "quantumult-x"
  | "loon"
  | "uri";

export interface CreateSubscriptionRequest {
  name: string;
  type: SubType;
  source_url?: string;
  ua?: string;
  sync_interval?: number;
  tags?: string[];
  remark?: string;
}

export interface UpdateSubscriptionRequest {
  name?: string;
  source_url?: string;
  ua?: string;
  sync_interval?: number;
  tags?: string[];
  remark?: string;
}

export interface SyncResult {
  subscription_id: string;
  node_count: number;
  added_count: number;
  removed_count: number;
  synced_at: number;
}

export interface PipelineBindingInput {
  pipeline_id: string;
  position: number;
  enabled: boolean;
}

export interface UpdatePipelineBindingsRequest {
  bindings: PipelineBindingInput[];
}

// ---------------------------------------------------------------------------
// M-NODE：节点 DTO
// ---------------------------------------------------------------------------

export interface Node {
  id: string;
  subscription_id: string;
  raw_uri: string;
  protocol: NodeProtocol;
  server: string;
  port: number;
  tag: string;
  tags: string[];
  is_chain_proxy: boolean;
  chain_parent_id?: string;
  parsed_config: Record<string, unknown>;
  position: number;
  created_at: number;
  updated_at: number;
}

export interface NodeWithLatency extends Node {
  latency_ms: number; // -1 = 不可达
  reachable: boolean;
  tested_at?: number;
}

export interface AddNodeRequest {
  raw_uri: string;
}

export interface UpdateNodeRequest {
  tags?: string[];
  chain_parent_id?: string;
}

export interface TCPingRequest {
  node_ids: string[];
  timeout_ms?: number;
  concurrency?: number;
}

export interface TCPingResult {
  node_id: string;
  latency_ms: number;
  reachable: boolean;
}

export interface TCPingResponse {
  results: TCPingResult[];
}

export interface SetChainRequest {
  parent_node_id: string; // 空字符串表示取消
}

// ---------------------------------------------------------------------------
// M-PIPE：流水线 DTO
// ---------------------------------------------------------------------------

export interface Pipeline {
  id: string;
  user_id: string;
  name: string;
  yaml_content: string;
  ast_json: string;
  version: number;
  schema_version: string;
  created_at: number;
  updated_at: number;
}

export interface PipelineOperator {
  id: string;
  type: OperatorType;
  enabled: boolean;
  params: FilterArgs | MapArgs | SortArgs | DedupeArgs | RegexRenameArgs | OutputArgs;
  position: number;
}

// 算子参数类型

export interface FilterArgs {
  expr: string;
}

export interface MapArgs {
  field: string;
  value: string;
}

export interface SortArgs {
  key: string;
  order: "asc" | "desc";
}

export interface DedupeArgs {
  fields: string[];
}

export interface RegexRenameArgs {
  pattern: string;
  replacement: string;
}

export interface OutputArgs {
  format: "clash" | "clash_meta" | "raw";
  max_nodes?: number;
}

export interface CreatePipelineRequest {
  name: string;
  yaml_content: string;
}

export interface UpdatePipelineRequest {
  name?: string;
  yaml_content: string;
  ast_json: string;
  version: number; // 乐观锁
}

export interface RunPipelineRequest {
  subscription_id: string;
  debug?: boolean;
}

export interface OperatorStepResult {
  operator: string;
  input_count: number;
  output_count: number;
  removed: string[];
  added: string[];
  modified: string[];
}

export interface RunPipelineResponse {
  total_ms: number;
  output_count: number;
  steps?: OperatorStepResult[];
}

export interface YAMLToASTRequest {
  yaml_content: string;
}

export interface ASTToYAMLRequest {
  ast_json: string;
}

export interface OperatorSchema {
  type: OperatorType;
  display_name: string;
  description: string;
  params_schema: unknown;
}

// ---------------------------------------------------------------------------
// M-RULE：规则 DTO
// ---------------------------------------------------------------------------

export interface CustomRule {
  id: string;
  user_id: string;
  name: string;
  type: RuleType;
  mode: RuleMode;
  content: string;
  enabled: boolean;
  sort: number;
  created_at: number;
  updated_at: number;
}

export interface CreateRuleRequest {
  name: string;
  type: RuleType;
  mode: RuleMode;
  content: string;
  enabled: boolean;
  sort?: number;
}

export interface UpdateRuleRequest {
  name?: string;
  mode?: RuleMode;
  content?: string;
  enabled?: boolean;
}

export interface RuleOrder {
  id: string;
  sort: number;
}

export interface UpdateRuleOrderRequest {
  orders: RuleOrder[];
}

export interface RuleTemplate {
  id: string;
  name: string;
  /** UI 显示用 emoji（如 🇭🇰）。 */
  emoji?: string;
  /** "region" | "app" | "block" | "common"。前端按 tab 分组。 */
  category?: string;
  description: string;
  rule_type?: RuleType;
  mode?: RuleMode;
  content: string;
  tags?: string[];
}

// ---------------------------------------------------------------------------
// M-RULE：规则集（Rule Provider）DTO
// ---------------------------------------------------------------------------

export type RuleSetBehavior = "domain" | "ipcidr" | "classical";
export type RuleSetFormat = "yaml" | "text" | "mrs";

export interface RuleSetProvider {
  id: string;
  user_id: string;
  name: string;
  behavior: RuleSetBehavior;
  format: RuleSetFormat;
  url: string;
  interval_seconds: number;
  enabled: boolean;
  last_synced_at?: number;
  last_sync_status?: string;
  last_sync_error?: string;
  created_at: number;
  updated_at: number;
}

export interface CreateRuleSetRequest {
  name: string;
  behavior: RuleSetBehavior;
  format: RuleSetFormat;
  url: string;
  interval_seconds?: number;
  enabled: boolean;
}

export interface UpdateRuleSetRequest {
  name?: string;
  behavior?: RuleSetBehavior;
  format?: RuleSetFormat;
  url?: string;
  interval_seconds?: number;
  enabled?: boolean;
}

export interface RuleSetPreset {
  id: string;
  name: string;
  emoji?: string;
  category: string; // "region" | "app" | "block"
  behavior: RuleSetBehavior;
  format: RuleSetFormat;
  url: string;
  interval_seconds: number;
  description?: string;
}

// ---------------------------------------------------------------------------
// M-RULE：代理组（Proxy Group）DTO
// ---------------------------------------------------------------------------

export type ProxyGroupType =
  | "select"
  | "url-test"
  | "fallback"
  | "load-balance"
  | "relay";

export interface ProxyGroupCategory {
  id: string;
  user_id: string;
  name: string;
  type: ProxyGroupType;
  icon?: string;
  sort_order: number;
  test_url?: string;
  test_interval?: number;
  filter?: string;
  include_all: boolean;
  member_proxies: string[];
  member_groups: string[];
  created_at: number;
  updated_at: number;
}

export interface CreateProxyGroupRequest {
  name: string;
  type: ProxyGroupType;
  icon?: string;
  sort_order?: number;
  test_url?: string;
  test_interval?: number;
  filter?: string;
  include_all?: boolean;
  member_proxies?: string[];
  member_groups?: string[];
}

export interface UpdateProxyGroupRequest {
  name?: string;
  type?: ProxyGroupType;
  icon?: string | null;
  sort_order?: number;
  test_url?: string | null;
  test_interval?: number;
  filter?: string | null;
  include_all?: boolean;
  member_proxies?: string[];
  member_groups?: string[];
}

export interface ProxyGroupReorderRequest {
  ids: string[];
}

export interface ProxyGroupPreset {
  id: string;
  name: string;
  type: ProxyGroupType;
  icon?: string;
  test_url?: string;
  test_interval?: number;
  filter?: string;
  include_all: boolean;
  member_proxies?: string[];
  member_groups?: string[];
  description?: string;
}

// ---------------------------------------------------------------------------
// M-SCRIPT：脚本 DTO
// ---------------------------------------------------------------------------

export interface Script {
  id: string;
  user_id: string;
  name: string;
  hook: HookType;
  code: string;
  enabled: boolean;
  last_run_at?: number;
  last_error?: string;
  created_at: number;
  updated_at: number;
}

export interface CreateScriptRequest {
  name: string;
  hook: HookType;
  code: string;
  enabled: boolean;
}

export interface UpdateScriptRequest {
  name?: string;
  code?: string;
  enabled?: boolean;
}

export interface ScriptTestRequest {
  sample_nodes: string; // JSON array string
}

export interface ScriptTestResponse {
  output_nodes: string; // JSON array string
  duration_ms: number;
  error?: string;
}

export interface ScriptLog {
  timestamp: number;
  level: string;
  message: string;
  error?: string;
}

// ---------------------------------------------------------------------------
// M-AGENT：探针 agent DTO
// ---------------------------------------------------------------------------

export interface Agent {
  id: string;
  user_id: string;
  name: string;
  kind: AgentKind;
  version?: string;
  os?: string;
  arch?: string;
  public_ip?: string;
  last_seen_at?: number;
  status: AgentStatus;
  created_at: number;
  updated_at: number;
  traffic_limit?: number;
  bwg_veid?: string;
  has_bwg_key?: boolean;
}

export interface AgentCreateResponse extends Agent {
  token: string; // 明文 token，仅此一次
  install_command: string;
  install_hint_i18n_key?: string; // nezha_compat 时的接入指引 i18n key
}

// agentListItem (server-side wraps Agent with online + latest_metrics).
// Lives here so the agent api hooks and list/detail components share a single
// shape consistent with internal/handler/agent_handler.go.
export interface AgentListItem extends Agent {
  online: boolean;
  latest_metrics?: AgentMetric;
}

export interface AgentMetric {
  agent_id: string;
  recorded_at: number;
  cpu_percent: number;
  cpu_cores?: number;
  mem_used: number;
  mem_total: number;
  swap_used: number;
  swap_total: number;
  disk_used: number;
  disk_total: number;
  net_in: number;
  net_out: number;
  net_in_speed: number;
  net_out_speed: number;
  load1: number;
  load5: number;
  load15: number;
  conn_tcp: number;
  conn_udp: number;
  uptime: number;
  process_count?: number;
}

export interface CreateAgentRequest {
  name: string;
  kind?: AgentKind; // 默认 "native"
  traffic_limit?: number;
  bwg_veid?: string;
  bwg_api_key?: string;
}

export interface UpdateAgentRequest {
  name?: string;
  traffic_limit?: number;
  bwg_veid?: string;
  bwg_api_key?: string;
}

export interface RotateTokenResponse {
  token: string;
}

// ---------------------------------------------------------------------------
// M-TRAFFIC：流量 DTO
// ---------------------------------------------------------------------------

export interface TrafficRecord {
  date: string; // YYYY-MM-DD
  user_id: string;
  agent_id?: string;
  total_limit?: number;
  total_used: number;
  total_in: number;
  total_out: number;
}

export interface AgentTrafficSummary {
  agent_id: string;
  agent_name: string;
  total_in: number;
  total_out: number;
  total_used: number;
  limit?: number;
  source?: string;
}

export interface TrafficSummary {
  user_id: string;
  period_start: string; // YYYY-MM-DD
  period_end: string;
  total_limit?: number;
  total_used: number;
  total_in: number;
  total_out: number;
  usage_percent: number;
  agents: AgentTrafficSummary[];
}

export interface TrafficChartPoint {
  date: string;
  total_in: number;
  total_out: number;
  agent_id?: string;
}

export interface TrafficThresholdRequest {
  threshold_percent: number; // 0-100
  total_limit?: number;
}

// ---------------------------------------------------------------------------
// M-NOTIFY：通知 DTO
// ---------------------------------------------------------------------------

export interface TelegramConfig {
  bot_token: string;
  chat_id: string;
  parse_mode?: "HTML" | "Markdown";
}

export interface DiscordConfig {
  webhook_url: string;
  username?: string;
}

export interface SlackConfig {
  webhook_url: string;
  channel?: string;
}

export interface EmailConfig {
  smtp_host: string;
  smtp_port: number;
  smtp_user: string;
  smtp_password: string;
  smtp_tls: boolean;
  from: string;
  to: string[];
}

export interface BarkConfig {
  device_key: string;
  server_url?: string;
}

export interface GotifyConfig {
  server_url: string;
  app_token: string;
}

export interface WebhookConfig {
  url: string;
  method?: "POST" | "GET";
  headers?: Record<string, string>;
}

export interface ServerChanConfig {
  send_key: string;
}

export interface PushDeerConfig {
  push_key: string;
  server_url?: string;
}

export interface IFTTTConfig {
  webhook_key: string;
  event_name: string;
}

export type ChannelConfig =
  | TelegramConfig
  | DiscordConfig
  | SlackConfig
  | EmailConfig
  | BarkConfig
  | GotifyConfig
  | WebhookConfig
  | ServerChanConfig
  | PushDeerConfig
  | IFTTTConfig;

export interface NotificationChannel {
  id: string;
  user_id: string;
  kind: ChannelKind;
  name: string;
  config: ChannelConfig;
  template?: string;
  event_types: EventType[];
  enabled: boolean;
  created_at: number;
  updated_at: number;
}

export interface CreateChannelRequest {
  kind: ChannelKind;
  name: string;
  config: ChannelConfig;
  template?: string;
  event_types: EventType[];
  enabled: boolean;
}

export interface UpdateChannelRequest {
  name?: string;
  config?: ChannelConfig;
  template?: string;
  event_types?: EventType[];
  enabled?: boolean;
}

export interface ChannelKindSchema {
  kind: ChannelKind;
  display_name: string;
  config_schema: unknown;
}

export interface NotificationEvent {
  id: number;
  user_id: string;
  channel_id?: string;
  event_type: EventType;
  payload: unknown;
  status: EventStatus;
  sent_at?: number;
  error?: string;
  created_at: number;
}

// ---------------------------------------------------------------------------
// M-OPS：短链 / OTA / 设置 / 审计 DTO
// ---------------------------------------------------------------------------

export interface ShortLink {
  file_code: string;
  user_code: string;
  user_id: string;
  target_url: string;
  short_url: string;
  expires_at?: number;
  created_at: number;
}

export interface CreateShortLinkRequest {
  target_url: string;
  expires_at?: number; // 0=永久
}

export interface OTAReleaseInfo {
  latest_version: string;
  current_version: string;
  has_update: boolean;
  release_url: string;
  changelog?: string;
  sha256: string;
  published_at: number;
}

export interface OTAHistoryItem {
  version: string;
  status: "success" | "failed";
  applied_at: number;
  error?: string;
}

export interface AuditLog {
  id: number;
  user_id?: string;
  action: string;
  resource_type?: string;
  resource_id?: string;
  ip?: string;
  user_agent?: string;
  payload?: unknown;
  success: boolean;
  created_at: number;
}

export interface SystemSetting {
  key: string;
  value: string;
  updated_at: number;
}

export interface SystemSettingsMap {
  silent_mode_enabled: boolean;
  silent_mode_prefix: string;
  session_ttl_seconds: number;
  monthly_reset_day: number;
  ota_check_interval: number;
  agent_heartbeat_interval: number;
  notification_debounce: number;
}

export interface UpdateSettingsRequest {
  silent_mode_enabled?: boolean;
  session_ttl_seconds?: number;
  monthly_reset_day?: number;
  ota_check_interval?: number;
  agent_heartbeat_interval?: number;
  notification_debounce?: number;
}

export interface SilentModeRequest {
  enabled?: boolean;
  rotate?: boolean;
}

export interface SilentModeResponse {
  enabled: boolean;
  prefix: string;
  login_url: string;
}

// ---------------------------------------------------------------------------
// M-ASSET：VPS 资产管理 DTO
// ---------------------------------------------------------------------------

export type VpsAssetStatus = "normal" | "expiring" | "expired";

export type BillingCycle =
  | "monthly"
  | "quarterly"
  | "semi_annual"
  | "annual"
  | "biennial"
  | "triennial";

export interface VpsAsset {
  id: string;
  user_id: string;
  name: string;
  ip?: string;
  ssh_port: number;
  ssh_user?: string;
  ssh_password?: string;
  ssh_private_key?: string;
  os?: string;
  location?: string;
  provider: string;
  price: number;
  currency: string;
  billing_cycle: BillingCycle;
  bandwidth?: string;
  monthly_traffic: number;
  cpu?: string;
  memory?: string;
  disk?: string;
  expire_at: string;
  notes?: string;
  agent_id?: string;
  tags: string[];
  created_at: string;
  updated_at: string;
  days_until_expiry: number;
  status: VpsAssetStatus;
}

export interface CreateVpsAssetRequest {
  name: string;
  ip?: string;
  ssh_port?: number;
  ssh_user?: string;
  ssh_password?: string;
  ssh_private_key?: string;
  os?: string;
  location?: string;
  provider: string;
  price: number;
  currency?: string;
  billing_cycle: BillingCycle;
  bandwidth?: string;
  monthly_traffic?: number;
  cpu?: string;
  memory?: string;
  disk?: string;
  expire_at: string;
  notes?: string;
  agent_id?: string;
  tags?: string[];
}

export interface UpdateVpsAssetRequest {
  name?: string;
  ip?: string | null;
  ssh_port?: number;
  ssh_user?: string | null;
  ssh_password?: string | null;
  ssh_private_key?: string | null;
  os?: string | null;
  location?: string | null;
  provider?: string;
  price?: number;
  currency?: string;
  billing_cycle?: BillingCycle;
  bandwidth?: string | null;
  monthly_traffic?: number;
  cpu?: string | null;
  memory?: string | null;
  disk?: string | null;
  expire_at?: string;
  notes?: string | null;
  agent_id?: string | null;
  tags?: string[];
}

export interface VpsAssetMonthlyCost {
  currency: string;
  monthly_cost: number;
}

export interface VpsAssetSummary {
  total: number;
  expiring: number;
  expired: number;
  monthly_cost: VpsAssetMonthlyCost[];
}

export interface VpsExpiryPayload {
  vps_id: string;
  vps_name: string;
  provider: string;
  days: number;
  expire_at: string;
}

// ---------------------------------------------------------------------------
// SSE 实时事件（hub → 前端，通过 /api/notify/stream）
// ---------------------------------------------------------------------------

export interface SSEAgentStatusPayload {
  agent_id: string;
  status: AgentStatus;
  ts: number;
}

export interface SSENotificationEventPayload {
  event_type: EventType;
  channel_id?: string;
  status: "sent" | "failed";
  ts: number;
}

export interface SSESubscriptionSyncPayload {
  subscription_id: string;
  status: SyncStatus;
  node_count?: number;
  error?: string;
  ts: number;
}

export interface SSESystemPayload {
  kind: "ota_available" | "settings_changed";
  version?: string;
  ts: number;
}

export type SSEEventPayload =
  | SSEAgentStatusPayload
  | SSENotificationEventPayload
  | SSESubscriptionSyncPayload
  | SSESystemPayload;

export interface SSEEvent {
  kind: "agent_status" | "notification_event" | "subscription_sync" | "system";
  payload: SSEEventPayload;
}
