// Code generated by api-contract. DO NOT EDIT.
// 修改本文件请同步更新：
//   - docs/04-api-contract.md
//   - internal/types/wsproto.go
//   - web/src/types/wsproto.ts
//
// pkg/agentlib 是 hub 和 agent 共同 import 的协议库。
// 向后兼容硬约束：已发布的字段不可删除，不可改类型。
// 新增字段必须用 omitempty 标记，以保证旧 agent 可正常通信。
package agentlib

import "encoding/json"

// ---------------------------------------------------------------------------
// 版本协商常量
// ---------------------------------------------------------------------------

// ProtocolVersion 当前协议版本号（语义版本）。
// hub 和 agent 通过 HelloPayload.Version 协商；
// 若 major 版本不匹配，hub 应拒绝连接并返回 bye 消息。
const ProtocolVersion = "1.0"

// ---------------------------------------------------------------------------
// 消息类型常量
// ---------------------------------------------------------------------------

// MessageType WebSocket 消息 type 字段枚举。
type MessageType string

const (
	MsgHello     MessageType = "hello"
	MsgHelloAck  MessageType = "hello_ack"
	MsgHeartbeat MessageType = "heartbeat"
	MsgMetrics   MessageType = "metrics"
	MsgCmd       MessageType = "cmd"
	MsgCmdAck    MessageType = "cmd_ack"
	MsgBye       MessageType = "bye"
)

// CmdType agent 可接受的命令类型。
type CmdType string

const (
	CmdRestart             CmdType = "restart"
	CmdRefreshSubscription CmdType = "refresh_subscription"
	// CmdUninstall: agent stops + removes itself (service + binary). Pushed by
	// the hub when an agent is deleted with uninstall=true.
	CmdUninstall CmdType = "uninstall"
	// 以下为 P2 预留，v1 hub 不会下发，agent 须忽略未知命令：
	CmdCollectNow CmdType = "collect_now"
	CmdShutdown   CmdType = "shutdown"
)

// AgentKind agent 类型。
type AgentKind string

const (
	KindNative      AgentKind = "native"
	KindNezhaCompat AgentKind = "nezha_compat"
)

// ---------------------------------------------------------------------------
// 通用信封
// ---------------------------------------------------------------------------

// Envelope 所有 WS 消息的外层信封。
// Payload 字段使用 json.RawMessage 以延迟解析，
// 接收方应先检查 Type 字段再选择具体 struct 解包。
type Envelope struct {
	Type    MessageType      `json:"type"`
	ID      string           `json:"id"`      // 消息唯一 ID（客户端用 uuid v4 生成）
	Payload json.RawMessage  `json:"payload"`
	TS      int64            `json:"ts"` // unix ms
}

// ---------------------------------------------------------------------------
// 握手（hello / hello_ack）
// ---------------------------------------------------------------------------

// HelloPayload agent → hub 握手 payload。
// 向后兼容：所有字段均为 v1 必填字段，后续新增字段须加 omitempty。
type HelloPayload struct {
	AgentID      string    `json:"agent_id"`
	Token        string    `json:"token"`
	OS           string    `json:"os"`
	Arch         string    `json:"arch"`
	Version      string    `json:"version"`
	Kind         AgentKind `json:"kind"`
	Capabilities []string  `json:"capabilities"` // ["metrics", "restart"]
}

// HelloAckPayload hub → agent 握手响应 payload。
type HelloAckPayload struct {
	OK                bool   `json:"ok"`
	HeartbeatInterval int32  `json:"heartbeat_interval"` // 秒，hub 下发，agent 必须遵守
	HubVersion        string `json:"hub_version"`
}

// ---------------------------------------------------------------------------
// 心跳（heartbeat）
// ---------------------------------------------------------------------------

// HeartbeatPayload agent → hub 轻量心跳 payload。
// 心跳与指标分离，以便 agent 在资源紧张时降低指标采集频率。
type HeartbeatPayload struct {
	AgentID string `json:"agent_id"`
	Uptime  int64  `json:"uptime"` // 秒，机器已运行时长
}

// ---------------------------------------------------------------------------
// 指标上报（metrics）
// ---------------------------------------------------------------------------

// MetricsPayload agent → hub 指标上报 payload。
//
// 向后兼容规则：
//   - 已有字段绝不可删除或改类型。
//   - 新增字段必须加 omitempty，旧 hub 收到后忽略即可。
//   - 字节型字段（网络/磁盘）使用 int64，避免 uint64 的 JSON 序列化问题。
type MetricsPayload struct {
	AgentID     string  `json:"agent_id"`
	CPUPercent  float64 `json:"cpu_percent"`
	CPUCores    int32   `json:"cpu_cores,omitempty"` // 逻辑核数（静态，新增字段）
	MemUsed     int64   `json:"mem_used"`
	MemTotal    int64   `json:"mem_total"`
	SwapUsed    int64   `json:"swap_used"`
	SwapTotal   int64   `json:"swap_total"`
	DiskUsed    int64   `json:"disk_used"`
	DiskTotal   int64   `json:"disk_total"`
	NetIn       int64   `json:"net_in"`        // 累计字节
	NetOut      int64   `json:"net_out"`       // 累计字节
	NetInSpeed  int64   `json:"net_in_speed"`  // B/s 瞬时
	NetOutSpeed int64   `json:"net_out_speed"` // B/s 瞬时
	Load1       float64 `json:"load1"`
	Load5       float64 `json:"load5"`
	Load15      float64 `json:"load15"`
	ConnTCP     int32   `json:"conn_tcp"`
	ConnUDP     int32   `json:"conn_udp"`
	Uptime      int64   `json:"uptime"` // 秒
	// v1.1 新增字段（omitempty，旧 hub 可安全忽略）：
	ProcessCount int32 `json:"process_count,omitempty"`
}

// ---------------------------------------------------------------------------
// 命令（cmd / cmd_ack）
// ---------------------------------------------------------------------------

// CmdPayload hub → agent 命令下发 payload。
// Args 为命令参数，各命令的参数 key 见下表（未来扩展用）：
//
//	restart:             无参数
//	refresh_subscription: { "subscription_id": "<id>" }（可选，空=刷新全部）
type CmdPayload struct {
	Cmd  CmdType           `json:"cmd"`
	Args map[string]string `json:"args,omitempty"`
}

// CmdAckPayload agent → hub 命令执行结果 payload。
type CmdAckPayload struct {
	CmdID string `json:"cmd_id"` // 对应 Envelope.ID
	OK    bool   `json:"ok"`
	Error string `json:"error,omitempty"`
}

// ---------------------------------------------------------------------------
// 断开通知（bye）
// ---------------------------------------------------------------------------

// ByePayload 断开通知 payload（任意方向均可发送）。
type ByePayload struct {
	Reason string `json:"reason,omitempty"` // "token_rotated" / "server_shutdown" / "idle_timeout"
}

// Bye reason 常量（§1.8 协议版本协商裁决）。
//
// 协议版本协商失败时 hub 发送 bye{ reason: "version_unsupported" } 后关闭连接，
// agent 收到此 reason 应停止重连并日志告警 "need upgrade"。
const (
	ByeReasonVersionUnsupported = "version_unsupported"
	ByeReasonServerShutdown     = "server_shutdown"
	ByeReasonTokenRotated       = "token_rotated"
	ByeReasonIdleTimeout        = "idle_timeout"
	ByeReasonAgentDeleted       = "agent_deleted"
)

// ---------------------------------------------------------------------------
// 编解码辅助函数（避免 agent 端引入 reflect 依赖）
// ---------------------------------------------------------------------------

// MarshalEnvelope 将信封序列化为 JSON 字节。
// agent 端所有 WS 发送均通过此函数，避免重复 json.Marshal 调用。
func MarshalEnvelope(env *Envelope) ([]byte, error) {
	return json.Marshal(env)
}

// UnmarshalEnvelope 从 JSON 字节解析信封（只解外层，payload 仍为 RawMessage）。
func UnmarshalEnvelope(data []byte) (*Envelope, error) {
	var env Envelope
	if err := json.Unmarshal(data, &env); err != nil {
		return nil, err
	}
	return &env, nil
}

// MarshalPayload 将 payload struct 序列化为 json.RawMessage，供构造 Envelope 使用。
func MarshalPayload(v any) (json.RawMessage, error) {
	return json.Marshal(v)
}

// UnmarshalHello 解析 hello payload。
func UnmarshalHello(raw json.RawMessage) (*HelloPayload, error) {
	var p HelloPayload
	return &p, json.Unmarshal(raw, &p)
}

// UnmarshalHelloAck 解析 hello_ack payload。
func UnmarshalHelloAck(raw json.RawMessage) (*HelloAckPayload, error) {
	var p HelloAckPayload
	return &p, json.Unmarshal(raw, &p)
}

// UnmarshalHeartbeat 解析 heartbeat payload。
func UnmarshalHeartbeat(raw json.RawMessage) (*HeartbeatPayload, error) {
	var p HeartbeatPayload
	return &p, json.Unmarshal(raw, &p)
}

// UnmarshalMetrics 解析 metrics payload。
func UnmarshalMetrics(raw json.RawMessage) (*MetricsPayload, error) {
	var p MetricsPayload
	return &p, json.Unmarshal(raw, &p)
}

// UnmarshalCmd 解析 cmd payload。
func UnmarshalCmd(raw json.RawMessage) (*CmdPayload, error) {
	var p CmdPayload
	return &p, json.Unmarshal(raw, &p)
}

// UnmarshalCmdAck 解析 cmd_ack payload。
func UnmarshalCmdAck(raw json.RawMessage) (*CmdAckPayload, error) {
	var p CmdAckPayload
	return &p, json.Unmarshal(raw, &p)
}

// UnmarshalBye 解析 bye payload。
func UnmarshalBye(raw json.RawMessage) (*ByePayload, error) {
	var p ByePayload
	return &p, json.Unmarshal(raw, &p)
}
