import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

/**
 * TanStack Router instance.
 * The routeTree is auto-generated by @tanstack/router-plugin from src/routes/.
 */
export const router = createRouter({ routeTree });

// Register the router for type safety.
declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}
