/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicTotpRouteImport } from './routes/_public/totp'
import { Route as PublicRecoveryRouteImport } from './routes/_public/recovery'
import { Route as PublicNotFoundRouteImport } from './routes/_public/not-found'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthedTrafficRouteImport } from './routes/_authed/traffic'
import { Route as AuthedRulesRouteImport } from './routes/_authed/rules'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedSubscriptionsIndexRouteImport } from './routes/_authed/subscriptions/index'
import { Route as AuthedScriptsIndexRouteImport } from './routes/_authed/scripts/index'
import { Route as AuthedProfileIndexRouteImport } from './routes/_authed/profile/index'
import { Route as AuthedPipelinesIndexRouteImport } from './routes/_authed/pipelines/index'
import { Route as AuthedNotificationsIndexRouteImport } from './routes/_authed/notifications/index'
import { Route as AuthedNodesIndexRouteImport } from './routes/_authed/nodes/index'
import { Route as AuthedAgentsIndexRouteImport } from './routes/_authed/agents/index'
import { Route as AuthedSubscriptionsIdRouteImport } from './routes/_authed/subscriptions/$id'
import { Route as AuthedScriptsScriptIdRouteImport } from './routes/_authed/scripts/$scriptId'
import { Route as AuthedProfile2faRouteImport } from './routes/_authed/profile/2fa'
import { Route as AuthedNotificationsTelegramRouteImport } from './routes/_authed/notifications/telegram'
import { Route as AuthedNotificationsChannelIdRouteImport } from './routes/_authed/notifications/$channelId'
import { Route as AuthedNodesNodeIdRouteImport } from './routes/_authed/nodes/$nodeId'
import { Route as AuthedAgentsAgentIdRouteImport } from './routes/_authed/agents/$agentId'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'
import { Route as AuthedAdminSettingsRouteImport } from './routes/_authed/admin/settings'
import { Route as AuthedAdminOtaRouteImport } from './routes/_authed/admin/ota'
import { Route as AuthedPipelinesPipelineIdEditRouteImport } from './routes/_authed/pipelines/$pipelineId/edit'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTotpRoute = PublicTotpRouteImport.update({
  id: '/totp',
  path: '/totp',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicRecoveryRoute = PublicRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicNotFoundRoute = PublicNotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthedTrafficRoute = AuthedTrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedRulesRoute = AuthedRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSubscriptionsIndexRoute =
  AuthedSubscriptionsIndexRouteImport.update({
    id: '/subscriptions/',
    path: '/subscriptions/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedScriptsIndexRoute = AuthedScriptsIndexRouteImport.update({
  id: '/scripts/',
  path: '/scripts/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProfileIndexRoute = AuthedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPipelinesIndexRoute = AuthedPipelinesIndexRouteImport.update({
  id: '/pipelines/',
  path: '/pipelines/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedNotificationsIndexRoute =
  AuthedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedNodesIndexRoute = AuthedNodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAgentsIndexRoute = AuthedAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSubscriptionsIdRoute = AuthedSubscriptionsIdRouteImport.update({
  id: '/subscriptions/$id',
  path: '/subscriptions/$id',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedScriptsScriptIdRoute = AuthedScriptsScriptIdRouteImport.update({
  id: '/scripts/$scriptId',
  path: '/scripts/$scriptId',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProfile2faRoute = AuthedProfile2faRouteImport.update({
  id: '/profile/2fa',
  path: '/profile/2fa',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedNotificationsTelegramRoute =
  AuthedNotificationsTelegramRouteImport.update({
    id: '/notifications/telegram',
    path: '/notifications/telegram',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedNotificationsChannelIdRoute =
  AuthedNotificationsChannelIdRouteImport.update({
    id: '/notifications/$channelId',
    path: '/notifications/$channelId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedNodesNodeIdRoute = AuthedNodesNodeIdRouteImport.update({
  id: '/nodes/$nodeId',
  path: '/nodes/$nodeId',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAgentsAgentIdRoute = AuthedAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminSettingsRoute = AuthedAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminOtaRoute = AuthedAdminOtaRouteImport.update({
  id: '/admin/ota',
  path: '/admin/ota',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPipelinesPipelineIdEditRoute =
  AuthedPipelinesPipelineIdEditRouteImport.update({
    id: '/pipelines/$pipelineId/edit',
    path: '/pipelines/$pipelineId/edit',
    getParentRoute: () => AuthedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/rules': typeof AuthedRulesRoute
  '/traffic': typeof AuthedTrafficRoute
  '/login': typeof PublicLoginRoute
  '/not-found': typeof PublicNotFoundRoute
  '/recovery': typeof PublicRecoveryRoute
  '/totp': typeof PublicTotpRoute
  '/admin/ota': typeof AuthedAdminOtaRoute
  '/admin/settings': typeof AuthedAdminSettingsRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/agents/$agentId': typeof AuthedAgentsAgentIdRoute
  '/nodes/$nodeId': typeof AuthedNodesNodeIdRoute
  '/notifications/$channelId': typeof AuthedNotificationsChannelIdRoute
  '/notifications/telegram': typeof AuthedNotificationsTelegramRoute
  '/profile/2fa': typeof AuthedProfile2faRoute
  '/scripts/$scriptId': typeof AuthedScriptsScriptIdRoute
  '/subscriptions/$id': typeof AuthedSubscriptionsIdRoute
  '/agents/': typeof AuthedAgentsIndexRoute
  '/nodes/': typeof AuthedNodesIndexRoute
  '/notifications/': typeof AuthedNotificationsIndexRoute
  '/pipelines/': typeof AuthedPipelinesIndexRoute
  '/profile/': typeof AuthedProfileIndexRoute
  '/scripts/': typeof AuthedScriptsIndexRoute
  '/subscriptions/': typeof AuthedSubscriptionsIndexRoute
  '/pipelines/$pipelineId/edit': typeof AuthedPipelinesPipelineIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/rules': typeof AuthedRulesRoute
  '/traffic': typeof AuthedTrafficRoute
  '/login': typeof PublicLoginRoute
  '/not-found': typeof PublicNotFoundRoute
  '/recovery': typeof PublicRecoveryRoute
  '/totp': typeof PublicTotpRoute
  '/admin/ota': typeof AuthedAdminOtaRoute
  '/admin/settings': typeof AuthedAdminSettingsRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/agents/$agentId': typeof AuthedAgentsAgentIdRoute
  '/nodes/$nodeId': typeof AuthedNodesNodeIdRoute
  '/notifications/$channelId': typeof AuthedNotificationsChannelIdRoute
  '/notifications/telegram': typeof AuthedNotificationsTelegramRoute
  '/profile/2fa': typeof AuthedProfile2faRoute
  '/scripts/$scriptId': typeof AuthedScriptsScriptIdRoute
  '/subscriptions/$id': typeof AuthedSubscriptionsIdRoute
  '/agents': typeof AuthedAgentsIndexRoute
  '/nodes': typeof AuthedNodesIndexRoute
  '/notifications': typeof AuthedNotificationsIndexRoute
  '/pipelines': typeof AuthedPipelinesIndexRoute
  '/profile': typeof AuthedProfileIndexRoute
  '/scripts': typeof AuthedScriptsIndexRoute
  '/subscriptions': typeof AuthedSubscriptionsIndexRoute
  '/pipelines/$pipelineId/edit': typeof AuthedPipelinesPipelineIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/rules': typeof AuthedRulesRoute
  '/_authed/traffic': typeof AuthedTrafficRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/not-found': typeof PublicNotFoundRoute
  '/_public/recovery': typeof PublicRecoveryRoute
  '/_public/totp': typeof PublicTotpRoute
  '/_authed/admin/ota': typeof AuthedAdminOtaRoute
  '/_authed/admin/settings': typeof AuthedAdminSettingsRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/_authed/agents/$agentId': typeof AuthedAgentsAgentIdRoute
  '/_authed/nodes/$nodeId': typeof AuthedNodesNodeIdRoute
  '/_authed/notifications/$channelId': typeof AuthedNotificationsChannelIdRoute
  '/_authed/notifications/telegram': typeof AuthedNotificationsTelegramRoute
  '/_authed/profile/2fa': typeof AuthedProfile2faRoute
  '/_authed/scripts/$scriptId': typeof AuthedScriptsScriptIdRoute
  '/_authed/subscriptions/$id': typeof AuthedSubscriptionsIdRoute
  '/_authed/agents/': typeof AuthedAgentsIndexRoute
  '/_authed/nodes/': typeof AuthedNodesIndexRoute
  '/_authed/notifications/': typeof AuthedNotificationsIndexRoute
  '/_authed/pipelines/': typeof AuthedPipelinesIndexRoute
  '/_authed/profile/': typeof AuthedProfileIndexRoute
  '/_authed/scripts/': typeof AuthedScriptsIndexRoute
  '/_authed/subscriptions/': typeof AuthedSubscriptionsIndexRoute
  '/_authed/pipelines/$pipelineId/edit': typeof AuthedPipelinesPipelineIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/rules'
    | '/traffic'
    | '/login'
    | '/not-found'
    | '/recovery'
    | '/totp'
    | '/admin/ota'
    | '/admin/settings'
    | '/admin/users'
    | '/agents/$agentId'
    | '/nodes/$nodeId'
    | '/notifications/$channelId'
    | '/notifications/telegram'
    | '/profile/2fa'
    | '/scripts/$scriptId'
    | '/subscriptions/$id'
    | '/agents/'
    | '/nodes/'
    | '/notifications/'
    | '/pipelines/'
    | '/profile/'
    | '/scripts/'
    | '/subscriptions/'
    | '/pipelines/$pipelineId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/rules'
    | '/traffic'
    | '/login'
    | '/not-found'
    | '/recovery'
    | '/totp'
    | '/admin/ota'
    | '/admin/settings'
    | '/admin/users'
    | '/agents/$agentId'
    | '/nodes/$nodeId'
    | '/notifications/$channelId'
    | '/notifications/telegram'
    | '/profile/2fa'
    | '/scripts/$scriptId'
    | '/subscriptions/$id'
    | '/agents'
    | '/nodes'
    | '/notifications'
    | '/pipelines'
    | '/profile'
    | '/scripts'
    | '/subscriptions'
    | '/pipelines/$pipelineId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_public'
    | '/_authed/dashboard'
    | '/_authed/rules'
    | '/_authed/traffic'
    | '/_public/login'
    | '/_public/not-found'
    | '/_public/recovery'
    | '/_public/totp'
    | '/_authed/admin/ota'
    | '/_authed/admin/settings'
    | '/_authed/admin/users'
    | '/_authed/agents/$agentId'
    | '/_authed/nodes/$nodeId'
    | '/_authed/notifications/$channelId'
    | '/_authed/notifications/telegram'
    | '/_authed/profile/2fa'
    | '/_authed/scripts/$scriptId'
    | '/_authed/subscriptions/$id'
    | '/_authed/agents/'
    | '/_authed/nodes/'
    | '/_authed/notifications/'
    | '/_authed/pipelines/'
    | '/_authed/profile/'
    | '/_authed/scripts/'
    | '/_authed/subscriptions/'
    | '/_authed/pipelines/$pipelineId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/totp': {
      id: '/_public/totp'
      path: '/totp'
      fullPath: '/totp'
      preLoaderRoute: typeof PublicTotpRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/recovery': {
      id: '/_public/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof PublicRecoveryRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/not-found': {
      id: '/_public/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof PublicNotFoundRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authed/traffic': {
      id: '/_authed/traffic'
      path: '/traffic'
      fullPath: '/traffic'
      preLoaderRoute: typeof AuthedTrafficRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/rules': {
      id: '/_authed/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AuthedRulesRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/subscriptions/': {
      id: '/_authed/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions/'
      preLoaderRoute: typeof AuthedSubscriptionsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/scripts/': {
      id: '/_authed/scripts/'
      path: '/scripts'
      fullPath: '/scripts/'
      preLoaderRoute: typeof AuthedScriptsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/profile/': {
      id: '/_authed/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthedProfileIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/pipelines/': {
      id: '/_authed/pipelines/'
      path: '/pipelines'
      fullPath: '/pipelines/'
      preLoaderRoute: typeof AuthedPipelinesIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/notifications/': {
      id: '/_authed/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthedNotificationsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/nodes/': {
      id: '/_authed/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof AuthedNodesIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/agents/': {
      id: '/_authed/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthedAgentsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/subscriptions/$id': {
      id: '/_authed/subscriptions/$id'
      path: '/subscriptions/$id'
      fullPath: '/subscriptions/$id'
      preLoaderRoute: typeof AuthedSubscriptionsIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/scripts/$scriptId': {
      id: '/_authed/scripts/$scriptId'
      path: '/scripts/$scriptId'
      fullPath: '/scripts/$scriptId'
      preLoaderRoute: typeof AuthedScriptsScriptIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/profile/2fa': {
      id: '/_authed/profile/2fa'
      path: '/profile/2fa'
      fullPath: '/profile/2fa'
      preLoaderRoute: typeof AuthedProfile2faRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/notifications/telegram': {
      id: '/_authed/notifications/telegram'
      path: '/notifications/telegram'
      fullPath: '/notifications/telegram'
      preLoaderRoute: typeof AuthedNotificationsTelegramRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/notifications/$channelId': {
      id: '/_authed/notifications/$channelId'
      path: '/notifications/$channelId'
      fullPath: '/notifications/$channelId'
      preLoaderRoute: typeof AuthedNotificationsChannelIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/nodes/$nodeId': {
      id: '/_authed/nodes/$nodeId'
      path: '/nodes/$nodeId'
      fullPath: '/nodes/$nodeId'
      preLoaderRoute: typeof AuthedNodesNodeIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/agents/$agentId': {
      id: '/_authed/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthedAgentsAgentIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/settings': {
      id: '/_authed/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthedAdminSettingsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/ota': {
      id: '/_authed/admin/ota'
      path: '/admin/ota'
      fullPath: '/admin/ota'
      preLoaderRoute: typeof AuthedAdminOtaRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/pipelines/$pipelineId/edit': {
      id: '/_authed/pipelines/$pipelineId/edit'
      path: '/pipelines/$pipelineId/edit'
      fullPath: '/pipelines/$pipelineId/edit'
      preLoaderRoute: typeof AuthedPipelinesPipelineIdEditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedRulesRoute: typeof AuthedRulesRoute
  AuthedTrafficRoute: typeof AuthedTrafficRoute
  AuthedAdminOtaRoute: typeof AuthedAdminOtaRoute
  AuthedAdminSettingsRoute: typeof AuthedAdminSettingsRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
  AuthedAgentsAgentIdRoute: typeof AuthedAgentsAgentIdRoute
  AuthedNodesNodeIdRoute: typeof AuthedNodesNodeIdRoute
  AuthedNotificationsChannelIdRoute: typeof AuthedNotificationsChannelIdRoute
  AuthedNotificationsTelegramRoute: typeof AuthedNotificationsTelegramRoute
  AuthedProfile2faRoute: typeof AuthedProfile2faRoute
  AuthedScriptsScriptIdRoute: typeof AuthedScriptsScriptIdRoute
  AuthedSubscriptionsIdRoute: typeof AuthedSubscriptionsIdRoute
  AuthedAgentsIndexRoute: typeof AuthedAgentsIndexRoute
  AuthedNodesIndexRoute: typeof AuthedNodesIndexRoute
  AuthedNotificationsIndexRoute: typeof AuthedNotificationsIndexRoute
  AuthedPipelinesIndexRoute: typeof AuthedPipelinesIndexRoute
  AuthedProfileIndexRoute: typeof AuthedProfileIndexRoute
  AuthedScriptsIndexRoute: typeof AuthedScriptsIndexRoute
  AuthedSubscriptionsIndexRoute: typeof AuthedSubscriptionsIndexRoute
  AuthedPipelinesPipelineIdEditRoute: typeof AuthedPipelinesPipelineIdEditRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedRulesRoute: AuthedRulesRoute,
  AuthedTrafficRoute: AuthedTrafficRoute,
  AuthedAdminOtaRoute: AuthedAdminOtaRoute,
  AuthedAdminSettingsRoute: AuthedAdminSettingsRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
  AuthedAgentsAgentIdRoute: AuthedAgentsAgentIdRoute,
  AuthedNodesNodeIdRoute: AuthedNodesNodeIdRoute,
  AuthedNotificationsChannelIdRoute: AuthedNotificationsChannelIdRoute,
  AuthedNotificationsTelegramRoute: AuthedNotificationsTelegramRoute,
  AuthedProfile2faRoute: AuthedProfile2faRoute,
  AuthedScriptsScriptIdRoute: AuthedScriptsScriptIdRoute,
  AuthedSubscriptionsIdRoute: AuthedSubscriptionsIdRoute,
  AuthedAgentsIndexRoute: AuthedAgentsIndexRoute,
  AuthedNodesIndexRoute: AuthedNodesIndexRoute,
  AuthedNotificationsIndexRoute: AuthedNotificationsIndexRoute,
  AuthedPipelinesIndexRoute: AuthedPipelinesIndexRoute,
  AuthedProfileIndexRoute: AuthedProfileIndexRoute,
  AuthedScriptsIndexRoute: AuthedScriptsIndexRoute,
  AuthedSubscriptionsIndexRoute: AuthedSubscriptionsIndexRoute,
  AuthedPipelinesPipelineIdEditRoute: AuthedPipelinesPipelineIdEditRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicNotFoundRoute: typeof PublicNotFoundRoute
  PublicRecoveryRoute: typeof PublicRecoveryRoute
  PublicTotpRoute: typeof PublicTotpRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicNotFoundRoute: PublicNotFoundRoute,
  PublicRecoveryRoute: PublicRecoveryRoute,
  PublicTotpRoute: PublicTotpRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
