/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicTotpRouteImport } from './routes/_public/totp'
import { Route as PublicRecoveryRouteImport } from './routes/_public/recovery'
import { Route as PublicNotFoundRouteImport } from './routes/_public/not-found'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedProfileIndexRouteImport } from './routes/_authed/profile/index'
import { Route as AuthedProfile2faRouteImport } from './routes/_authed/profile/2fa'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTotpRoute = PublicTotpRouteImport.update({
  id: '/totp',
  path: '/totp',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicRecoveryRoute = PublicRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicNotFoundRoute = PublicNotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProfileIndexRoute = AuthedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProfile2faRoute = AuthedProfile2faRouteImport.update({
  id: '/profile/2fa',
  path: '/profile/2fa',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/login': typeof PublicLoginRoute
  '/not-found': typeof PublicNotFoundRoute
  '/recovery': typeof PublicRecoveryRoute
  '/totp': typeof PublicTotpRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/profile/2fa': typeof AuthedProfile2faRoute
  '/profile/': typeof AuthedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/login': typeof PublicLoginRoute
  '/not-found': typeof PublicNotFoundRoute
  '/recovery': typeof PublicRecoveryRoute
  '/totp': typeof PublicTotpRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/profile/2fa': typeof AuthedProfile2faRoute
  '/profile': typeof AuthedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/not-found': typeof PublicNotFoundRoute
  '/_public/recovery': typeof PublicRecoveryRoute
  '/_public/totp': typeof PublicTotpRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/_authed/profile/2fa': typeof AuthedProfile2faRoute
  '/_authed/profile/': typeof AuthedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/not-found'
    | '/recovery'
    | '/totp'
    | '/admin/users'
    | '/profile/2fa'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/not-found'
    | '/recovery'
    | '/totp'
    | '/admin/users'
    | '/profile/2fa'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_public'
    | '/_authed/dashboard'
    | '/_public/login'
    | '/_public/not-found'
    | '/_public/recovery'
    | '/_public/totp'
    | '/_authed/admin/users'
    | '/_authed/profile/2fa'
    | '/_authed/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/totp': {
      id: '/_public/totp'
      path: '/totp'
      fullPath: '/totp'
      preLoaderRoute: typeof PublicTotpRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/recovery': {
      id: '/_public/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof PublicRecoveryRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/not-found': {
      id: '/_public/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof PublicNotFoundRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/profile/': {
      id: '/_authed/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthedProfileIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/profile/2fa': {
      id: '/_authed/profile/2fa'
      path: '/profile/2fa'
      fullPath: '/profile/2fa'
      preLoaderRoute: typeof AuthedProfile2faRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
  AuthedProfile2faRoute: typeof AuthedProfile2faRoute
  AuthedProfileIndexRoute: typeof AuthedProfileIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
  AuthedProfile2faRoute: AuthedProfile2faRoute,
  AuthedProfileIndexRoute: AuthedProfileIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicNotFoundRoute: typeof PublicNotFoundRoute
  PublicRecoveryRoute: typeof PublicRecoveryRoute
  PublicTotpRoute: typeof PublicTotpRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicNotFoundRoute: PublicNotFoundRoute,
  PublicRecoveryRoute: PublicRecoveryRoute,
  PublicTotpRoute: PublicTotpRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
